### ISSUE TITLE
Test Twilio Settings?

### ISSUE THREAD

**Issue by nasell** [ianmarmour/nvidia-clerk#1]
Thank you for this!

Is there a flag option we can add to test our SMS settings?

**Comment by ianmarmour** [comment]
I can get something added to do test verification for Twilio, I was manually testing by flipping notifications on and off. I'm going to backlog this in favor of getting the shopping cart fixes out first, but after shopping cart stuff is done I'll look into this as well.

**Comment by nasell** [comment]
Yeah, no worries! Maybe even just a -force-instock option so the app trips just like you did in code. 

Thanks again for all of your work here! Ready for tomorrow (I think! I should be at my desk regardless, so not as concerned with my dev twilio account)!

**Comment by ianmarmour** [comment]
Added a -test option flag that can validate your Twilio settings, I also fixed up a bug preventing Twilio from working, going to go ahead and close this.
