### ISSUE TITLE
Index out of range (GB)

### ISSUE THREAD

**Issue by cthuluke** [ianmarmour/nvidia-clerk#10]
Variables:
SKU: 5438792800 (Great Britain RTX 3080)
Locale: en_GB
Currency:  GBP

Receive the error below as soon I run the exe.

Exception:
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.main()
goroutine 1 [running]:main.main()/home/inarm/go/src/github.com/ianmarmour/nvidia-clerk/main.go:59 +0x746

**Comment by ianmarmour** [comment]
What platform are you running on? (windows, mac, linux) and what shell are you using?

**Comment by cthuluke** [comment]
Sorry, platform is Windows.
And I'm not nearly tech savvy enough to understand what a shell is, but an educated guess says, I'm using Command Prompt, is that the correct answer? lol

**Comment by ianmarmour** [comment]
Yep that's the correct answer haha :).

Do you have Google Chrome installed on your system?

**Comment by cthuluke** [comment]
I do, although running the exe via Command Prompt brings up a separate version of Chrome (evident by the fact the none of my extensions exist within the window it brings up), is that normal?

**Comment by ianmarmour** [comment]
Yep that's to be expected and indicates that it's running properly, 

This is the main link that the tool uses to get information and looks like it's working with your configuration,

https://in-and-ru-store-api.uk-e1.cloudhub.io/DR/products/en_GB/GBP/5438792800

can you post me the commands you're running :)

**Comment by cthuluke** [comment]
Ah, update, I was previously copy/pasting in all 3 NVIDIA_SET commands and hitting enter after each one before dragging in the file. Now to make life easier, I just wrote out and copy pasted the entire thing:

> set NVIDIA_CLERK_SKU=5438792800
> set NVIDIA_CLERK_LOCALE=en_GB
> set NVIDIA_CLERK_CURRENCY=GBP

before hitting enter, and then dragging in the exe.

The Command Prompt now repeatedly prints:

> SKU Name: NVIDIA GEFORCE RTX 3080 - GB
> SKU Status: PRODUCT INVENTORY_OUT_OF_STOCK
> Product Inventory: 2

Occasionally printing an 'Invalid Character' code, which worries me, but then it seems to go back to printing the stock information after a while.

In the chrome window, it only displays the 'access_token' tab, will it only open up a new tab to the nvidia store when it detects it can add a card to my cart?

**Comment by ianmarmour** [comment]
That's totally correct yep, what you're getting now is the intended behavior. From time to time you'll get the invalid character code that's just NVIDIAs inventory timing out from too many requests, unless you're getting a solid wall of those there's nothing to worry about. 

You'll need to leave both the browser and the command line tool open (but can be minimized), whenever the inventory comes in stock it will automatically drop you into a checkout in that chrome browser.

**Comment by cthuluke** [comment]
Brilliant, thanks very much! Great work :D
