### ISSUE TITLE
Error on newest version

### ISSUE THREAD

**Issue by fokeiro2020** [ianmarmour/nvidia-clerk#100]
with newest version getting this error below and script stop.

![Untitled](https://user-images.githubusercontent.com/71787372/94220760-b2c5d000-feb7-11ea-8a73-5de88d82cbd6.png)

**Comment by Qerlak** [comment]
Getting the same behavior. One check and then stops

**Comment by facetsu** [comment]
Same problem here. Tried a few regions and still fails.

**Comment by captainbraz** [comment]
Same issue

**Comment by reubenprevost** [comment]
If you are able to edit the source there is a break statement on line 90 of main.go

remove that and it will work.

**Comment by fokeiro2020** [comment]
> If you are able to edit the source there is a break statement on line 90 of main.go
> 
> remove that and it will work.

using the  win .exe version

**Comment by reubenprevost** [comment]
I'm sure he will fix it soon.

**Comment by ianmarmour** [comment]
This is fixed in 3.5 go download latest (also extra logging is removed)
