### ISSUE TITLE
Break on line 90 - main.go

### ISSUE THREAD

**Issue by reubenprevost** [ianmarmour/nvidia-clerk#101]
Break on line 90 in main.go breaks the loop

Also -discord flag and -remote flag causes problems

V3.2

**Comment by ianmarmour** [comment]
Yep sorry about that, using test mode only iterates a single time and I'm not testing the main loop sigh. Removed 3.3, I've been testing sms and that's been working still trying to look into discord (I had thought it was fixed but I guess I was wrong)

**Comment by fokeiro2020** [comment]
> Yep sorry about that, using test mode only iterates a single time and I'm not testing the main loop sigh. Removed 3.3, I've been testing sms and that's been working still trying to look into discord (I had thought it was fixed but I guess I was wrong)

sms is sending a bad link to an empty shopping cart

**Comment by ianmarmour** [comment]
@fokeiro2020 Can you run it a few times, apparently we've been seeing inconsistent results with the sms (I've had it work on LAN/LTE and after clearing my browser cache multiple times). Other folks haven't.

**Comment by reubenprevost** [comment]
> > Yep sorry about that, using test mode only iterates a single time and I'm not testing the main loop sigh. Removed 3.3, I've been testing sms and that's been working still trying to look into discord (I had thought it was fixed but I guess I was wrong)
> 
> sms is sending a bad link to an empty shopping cart

I'm curious, what mobile OS are you using (andriod or IOS)?
also, are you using a web interface to access your messages (like messages.google.com)?

@ianmarmour Do you think it's because these apps like discord are accessing the link first? I really don't know, just guessing.

**Comment by ianmarmour** [comment]
I'm using messenger built into IOS (and yes, that's one theory I have)

**Comment by fokeiro2020** [comment]
> > > Yep sorry about that, using test mode only iterates a single time and I'm not testing the main loop sigh. Removed 3.3, I've been testing sms and that's been working still trying to look into discord (I had thought it was fixed but I guess I was wrong)
> > 
> > 
> > sms is sending a bad link to an empty shopping cart
> 
> I'm curious, what mobile OS are you using (andriod or IOS)?
> also, are you using a web interface to access your messages (like messages.google.com)?
> 
> @ianmarmour Do you think it's because these apps like discord are accessing the link first? I really don't know, just guessing.

Android s10+ , google sms app and link open to chrome

**Comment by ianmarmour** [comment]
@rjprevost So just verified manually sending a link through gmail to someone else.... that worked fine, did the same thing via discord and it breaks...

Pretty sure discord is monitoring people's posted links and visiting them.... real creepy.

**Comment by reubenprevost** [comment]
Yeah, that's what I'm thinking.

I think Google sms is doing the same thing, though I've only tested it via their webapp (messages.google.com)

**Comment by ianmarmour** [comment]
Yeah I'm 99.99% sure this is why :/ not really sure the best way to get around this (but hey it's nice to know Apple isn't harvesting url metadata on cellphones (maybe they are concerned about privacy)

**Comment by ianmarmour** [comment]
revert for now this is an easy fix but I'm going to bundle it with the notifications changes.

**Comment by ianmarmour** [comment]
So I think I may have cracked it... pretty sure discord attempts auto embeds unless you wrap a link in <>

**Comment by reubenprevost** [comment]
That makes sense. I'll test it real quick.

**Comment by ianmarmour** [comment]
[nvidia-clerk-windows.zip](https://github.com/ianmarmour/nvidia-clerk/files/5280495/nvidia-clerk-windows.zip)
Here's a build with the change

**Comment by reubenprevost** [comment]
I'm running a mac, but I think it worked for me. Just added the <> and it seemed to work fine.

**Comment by ianmarmour** [comment]
Awesome also for your sms, I think you can just disable the link preview feature on android.

**Comment by reubenprevost** [comment]
Not going to test sms right now, but Discord is working consistently. That fixed it.

**Comment by ndemos** [comment]
Disabling link preview fixed the sms link for me! Good catch.

**Comment by ianmarmour** [comment]
https://github.com/ianmarmour/nvidia-clerk/releases/tag/v3.5
