### ISSUE TITLE
Runtime unknown

### ISSUE THREAD

**Issue by HiramIII** [ianmarmour/nvidia-clerk#102]
I have screenshots of the issue https://imgur.com/a/Jux6rY2

This is happening on the latest version.

**Comment by reubenprevost** [comment]
Are you on 32bit or 64bit windows?

**Comment by HiramIII** [comment]
> 
> 
> Are you on 32bit or 64bit windows?

64 bit

**Comment by HiramIII** [comment]
v3.6 is also giving the same issues

**Comment by HiramIII** [comment]
Actually getting the same error codes from earlier @ianmarmour

**Comment by reubenprevost** [comment]
Your issue is beyond my knowledge. It seems like a low-level issue with memory addresses. I'll try googling it shortly.

**Comment by ianmarmour** [comment]
Mine too, it sounds like antivirus or security software or a hardware/golang runtime error.

**Comment by HiramIII** [comment]
@ianmarmour These are the error issues now: https://imgur.com/a/4WfA6qf

**Comment by reubenprevost** [comment]
I compiled my own and it works fine. 

Other people ran into this problem when compiling with certain AV software.

**Comment by reubenprevost** [comment]
You can try that. Everything will be the same except the file is called main.exe. This is based on 3.5 as well.
[main.exe.zip](https://github.com/ianmarmour/nvidia-clerk/files/5280650/main.exe.zip)

**Comment by HiramIII** [comment]
v3.6 fixed the issue @rjprevost @ianmarmour
