### ISSUE TITLE
Token error checking.

### ISSUE THREAD

**Issue by reubenprevost** [ianmarmour/nvidia-clerk#103]
for token == nil {
		sleep(delay)
		token, err = rest.GetSessionToken(client)
		if err != nil {
			log.Printf("Error getting session token from NVIDIA retrying...")
			continue
		}
	}

This is missing. So if the user runs into that error, the script will end

**Comment by ianmarmour** [comment]
Yeah I took it out because I was quite a few failures and I'm concerned that that retrying for the token that frequently might get someone throttled. If you get an error you should wait but maybe it would be better to just delay for like 30/45 seconds rather then a few.

**Comment by reubenprevost** [comment]
Yeah, that makes sense.
