### ISSUE TITLE
Telegrams notifications not working. 

### ISSUE THREAD

**Issue by carlouws** [ianmarmour/nvidia-clerk#104]
The Telegram test flag is not working and I'm also not receiving the instock notification using the `-model=2060` and I'm also not receiving the link when using `-remote`

I was able to double check my API key and chat id are correct using this method:

`https://api.telegram.org/bot**API_KEY_HERE**/sendMessage?chat_id=**CHAT_ID_HERE**&text=TEST123` and I was able to receive the test message.

**Comment by ianmarmour** [comment]
I didn't have telegram to test, let me update it and send out a test build on here to verify.

**Comment by ianmarmour** [comment]
[nvidia-clerk-windows.zip](https://github.com/ianmarmour/nvidia-clerk/files/5280908/nvidia-clerk-windows.zip)
Test build hopefully this works? Let me know.

**Comment by MrMightyNighty** [comment]
Same here. Updated from 3.0 to 3.6 and not working anymore. Linux

**Comment by ianmarmour** [comment]
[nvidia-clerk.zip](https://github.com/ianmarmour/nvidia-clerk/files/5281092/nvidia-clerk.zip)
Linux executable for testing too @MrMightyNighty

**Comment by MrMightyNighty** [comment]
No notification with the executable. Telegram works with <=v3.1

**Comment by StanleyAlbayeros** [comment]
I can't make telegram work with anything higher than v3.1 either. I tried the windows and the Linux versions @ianmarmour just posted here and no luck either. Currently sticking to v3.1

**Comment by carlouws** [comment]
> [nvidia-clerk-windows.zip](https://github.com/ianmarmour/nvidia-clerk/files/5280908/nvidia-clerk-windows.zip)
> Test build hopefully this works? Let me know.

Didn't work for me. @ianmarmour 
Would like to add that Telegram is working for me with Version 3.1

**Comment by ianmarmour** [comment]
I'm testing a fix for this right now (finally caved and just setup telegram to verify), but the nvidia shop API is down right now so I'm I can't validate :'(

**Comment by carlouws** [comment]
Don't know if the possible fix was pushed to the latest release but Telegram still isn't working. I did the Twilio setup and it is working perfectly. Using Twilio for now.

**Comment by ianmarmour** [comment]
Pushing a fix for this right now, I had to setup telegram for local testing sorry about that.

**Comment by ianmarmour** [comment]
Please see,

https://github.com/ianmarmour/nvidia-clerk/releases/tag/v3.7.4

This works now.

**Comment by carlouws** [comment]
Thanks a lot. Working perfectly.
