### ISSUE TITLE
Enhancement? Add @here to discord

### ISSUE THREAD

**Issue by captainbraz** [ianmarmour/nvidia-clerk#105]
Not sure if it's possible to add @here to the discord notification, but for some reason I can't get it to notify on mobile even with all the notification settings set to "all". wondering if an @here would help

**Comment by fokeiro2020** [comment]
> Not sure if it's possible to add @here to the discord notification, but for some reason I can't get it to notify on mobile even with all the notification settings set to "all". wondering if an @here would help

have same problem on discord yesterday, notifications just stopped working

**Comment by ianmarmour** [comment]
Closing this in favor of #107 it makes more sense to use generalized discord message customization then it does to provide specifically adding the here flag depending on what users want.
