### ISSUE TITLE
Unable to test the remote feature with 3.6 using region GBR

### ISSUE THREAD

**Issue by callrua** [ianmarmour/nvidia-clerk#106]
Operating system: Red Hat 8 Linux & Windows 10
Version of nvidia-clerk you're running: 3.6 
Parameters passed in (redact sensitive info): -telegram -model=2070 -region=GBR -remote 
Additional info:

./nvidia-clerk-linux -telegram -model=2070 -region=GBR -remote 
```
panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6827b3]
goroutine 1 [running]:
main.main()
        /home/runner/work/nvidia-clerk/nvidia-clerk/main.go:53 +0x553
```

In comparisson: 

```
./nvidia-clerk-linux -telegram -model=3080 -region=GBR -remote 
2020/09/25 08:18:48 Product ID: 5438792800
2020/09/25 08:18:48 Product Name: NVIDIA GEFORCE RTX 3080 - GB
2020/09/25 08:18:48 Product Locale: en_gb
2020/09/25 08:18:48 Product Status: PRODUCT_INVENTORY_OUT_OF_STOCK
2020/09/25 08:18:50 Product ID: 5438792800
2020/09/25 08:18:50 Product Name: NVIDIA GEFORCE RTX 3080 - GB
2020/09/25 08:18:50 Product Locale: en_gb
2020/09/25 08:18:50 Product Status: PRODUCT_INVENTORY_OUT_OF_STOCK
2020/09/25 08:18:51 Product ID: 5438792800
2020/09/25 08:18:51 Product Name: NVIDIA GEFORCE RTX 3080 - GB
2020/09/25 08:18:51 Product Locale: en_gb
2020/09/25 08:18:51 Product Status: PRODUCT_INVENTORY_OUT_OF_STOCK
```

**Comment by callrua** [comment]
FYI this same happens on 2060, 2070 & 2080 params.

**Comment by MrMightyNighty** [comment]
From the Readme: "Testing is currenly only supported for the USA region but it should show you what the automated checkout will look like."

Also "-test" is missing and model should be 2060.

**Comment by MrMightyNighty** [comment]
nvidia-clerk-linux -telegram -model=2060 -test -remote

But FYI Telegram currently doesn't work with 3.6 (#104)

**Comment by callrua** [comment]
Gotcha, missed that, just skimmed the docs this morning.

-test not actually needed for this test case, and as mentioned broken on all 2xxx models. 

I'll close this one off anyway, I was just double checking if there was a way to get it to work fully in GBR, the US test is enough for now.

Cheers.
