### ISSUE TITLE
Request: Compile for Arm Linux

### ISSUE THREAD

**Issue by MadEngineer75** [ianmarmour/nvidia-clerk#108]
Can you also compile for Arm Linux to use on a Raspberry Pi since it's more power efficient? I've compiled the code myself on my Pi, but I don't want to create a fork just for another architecture.

The only change the is needed to the code to compile on for Arm Linux is to change the variable type of "ID" in the structs of "Product" and "RelatedProduct" in the nvidia.go file. In the Arm architecture a variable type of "int" defaults to a 32bit int, which won't fit the product SKU. So you just have to explicitly declare the variables as an "int64" to make the program work on Arm.

**Comment by ianmarmour** [comment]
@MadScientist75 Hey nice request :), I would be happy to, I'll get a new build posted soon.

**Comment by ianmarmour** [comment]
@MadScientist75 

https://github.com/ianmarmour/nvidia-clerk/releases/tag/v3.7.2

Closing :)
