### ISSUE TITLE
Error attempting to get product information retrying...

### ISSUE THREAD

**Issue by coolfarmer** [ianmarmour/nvidia-clerk#109]
```
nvidia-clerk-windows.exe -sms -region=CAN -model=3080
Error attempting to get product information retrying...
```
It was working fine during the night and now I get that error, not working anymore! :(

**Comment by redstone2019** [comment]
The 3090 SKU on the Canadian region is also having problems

`C:\Users\#####\nvidia-clerk-windows.exe -region=CAN -model=3090`
`panic: runtime error: invalid memory address or nil pointer dereference`
`[signal 0xc0000005 code=0x0 addr=0x0 pc=0x68613f]`

`goroutine 1 [running]:`
`main.main()`
        `/home/runner/work/nvidia-clerk/nvidia-clerk/main.go:53 +0x55f`

**Comment by ianmarmour** [comment]
Related to #116 closing track there for updates.
