### ISSUE TITLE
Intermittent errors

### ISSUE THREAD

**Issue by Coveredz** [ianmarmour/nvidia-clerk#11]
Getting the following intermittent errors:

invalid character '<' looking for beginning of value
Error getting SKU Information retrying...
invalid character '<' looking for beginning of value
Error getting SKU Information retrying...
invalid character '<' looking for beginning of value
Error getting SKU Information retrying...
SKU Name: NVIDIA GEFORCE RTX 3080 - FR
SKU Status: PRODUCT_INVENTORY_OUT_OF_STOCK
Product Inventory: 7

Error attempting to access URL: https://in-and-ru-store-api.uk-e1.cloudhub.io/DR/get-inventory/fr_fr/5438795200?format=json&expand=availablequantity
Error getting SKU Inventory retrying...
Error attempting to access URL: https://in-and-ru-store-api.uk-e1.cloudhub.io/DR/products/fr_fr/EUR/5438795200
Error getting SKU Information retrying...
SKU Name: NVIDIA GEFORCE RTX 3080 - FR
SKU Status: PRODUCT_INVENTORY_OUT_OF_STOCK
Product Inventory: 7

invalid character '<' looking for beginning of value
Error getting SKU Information retrying...
invalid character '<' looking for beginning of value
Error getting SKU Information retrying...
invalid character '<' looking for beginning of value
Error getting SKU Inventory retrying...
invalid character '<' looking for beginning of value
Error getting SKU Information retrying...
invalid character '<' looking for beginning of value
Error getting SKU Information retrying...
invalid character '<' looking for beginning of value
Error getting SKU Information retrying...
Error attempting to access URL: https://in-and-ru-store-api.uk-e1.cloudhub.io/DR/products/fr_fr/EUR/5438795200
Error getting SKU Information retrying...
invalid character '<' looking for beginning of value
Error getting SKU Information retrying...
invalid character '<' looking for beginning of value
Error getting SKU Information retrying...
Error attempting to access URL: https://in-and-ru-store-api.uk-e1.cloudhub.io/DR/products/fr_fr/EUR/5438795200
Error getting SKU Information retrying...

**Comment by PedroC1999** [comment]
After working for an hour or so I am also getting these issues more commonly now

**Comment by cthuluke** [comment]
I'm also getting this now, after a good hour or so of it working absolutely fine.
From the UK store.

**Comment by AlexandreSoteras** [comment]
Same here, it was working fine a few minutes ago

Edit : It's probably not related to the code, as the Nvidia URL seems down : https://in-and-ru-store-api.uk-e1.cloudhub.io/DR/products/fr_FR/EUR/5438795200

**Comment by forestlovewood** [comment]
It looks like the products information is returning a gateway timeout – I'm wondering if this may be preventative measures being put in place to disable bots. Additionally to this, I've noticed that, in the UK, the product ID / SKU comes up as not found when attempting to add to cart, when previously it would simply say it was out of stock.

Edit: I think it's simply that the API has gone down for some reason, probably all the people hammering it with stock requests...

**Comment by mychaelhoward** [comment]
No longer seems to be working for me. Just "Error getting sku information retrying"

**Comment by Coveredz** [comment]
Yes, as @Creepymulder said, the query URL is now down altogether. Maybe we just broke it by flooding it with requests!

**Comment by AlexandreSoteras** [comment]
At first I thought I was ban or something, but I still can't reach this URL on a different network. You can even see the issue directly on their website where they have the "buy" button loading indefinitely for others cards.  I guess we just have to wait :]

**Comment by cthuluke** [comment]
Has anybody had any updates on this issue so far? I wonder if simply starting the process again might do something, I'll try myself soon but wondered if anyone else had already attempt it.

**Comment by forestlovewood** [comment]
@cthuluke As far as I can tell their API is still broken, so there's no change there, including for existing, in-stock products.

**Comment by cthuluke** [comment]
@forestlovewood gotcha, in the case that there is a re-stock in nvidia stores 45 minutes from now, would their API being broken affect being able to manually see and add the item to cart, or will it make the item unpurchaseable by any means for as long as it's broken?

**Comment by forestlovewood** [comment]
@cthuluke I wasn't able to add any products to the basket, so I think it wouldn't be possibly to purchase any.

Edit: Loading product information returns a 503 or 504, while adding to the cart returns "Could not find a Product resource with an id of 5438792800", at least for this product. Adding to the cart seems to use this process. This is United Kingdom specific as other regions have different product IDs.

1. Visit `https://store.nvidia.com/store/nvidia/SessionToken?format=json&locale=en_us&apiKey=9485fa7b159e42edb08a83bde0d83dia` which will return your current `access_token`.
2. Visit `https://api.digitalriver.com/v1/shoppers/me/carts/active/line-items?format=json&method=post&productId=5438792800&quantity=1&token={the previous access_token}`
3. Visit `https://api.digitalriver.com/v1/shoppers/me/carts/active/web-checkout?productId=5438792800&token={the previous access_token}`

**Comment by cthuluke** [comment]
Yeah, also returns 'product could not be found' errors for me. Does that mean they might have changed the ID of the product? My hope is that whilst we can't be alerted to them or add them to cart, neither can bots haha. I have that fear-of-missing-out.

**Comment by forestlovewood** [comment]
@cthuluke I thought so, but checking their product listings it seems to still be the same.

**Comment by cthuluke** [comment]
Hey guys, just so I can do some testing, how does one find the product ID of an item? For example if I wanted to try adding an 2080 from the GB store in my basket using this script for the sake of experimenting, how is that ID found?

**Comment by forestlovewood** [comment]
@cthuluke `https://api.digitalriver.com/v1/shoppers/me/products?apiKey=9485fa7b159e42edb08a83bde0d83dia&locale=en_gb&format=json&expand=product&fields=product.id,product.displayName,product.pricing&pageNumber=7`

I see all products seem to come up as not found now.

**Comment by longgaminghours** [comment]
Is this broken now?

**Comment by cthuluke** [comment]
Mine seems to be running and giving me the product information for the 3080.
However whether that is false information based on an now defunct product ID, who knows!?

**Comment by AlexandreSoteras** [comment]
It's working for me, I updated it a bit to refresh every 2 seconds because it was a bit aggressive, the URL was showing an "Exceeding limit error" of the API, I prefer to bit a bit careful not to get ban.

**Comment by longgaminghours** [comment]
I just get the Error getting SKU information retrying.

**Comment by javitab** [comment]
The errors are still intermittent but i used the call provided by @forestlovewood and adapted it for en-us, found the SKU for a 2060 FE, tested with that, I got a browser pop up with a 2060 in my cart and a text on my phone letting me know that it's in my cart ready to go. Put the SKU back to the 3080 and it's humming along.

**Comment by longgaminghours** [comment]
@arbyyyyh looks like all jibbersih to me.

**Comment by ianmarmour** [comment]
> Is this broken now?

Not as far as I know, I'm still running it fine in the US region.

**Comment by ianmarmour** [comment]
> @cthuluke I wasn't able to add any products to the basket, so I think it wouldn't be possibly to purchase any.
> 
> Edit: Loading product information returns a 503 or 504, while adding to the cart returns "Could not find a Product resource with an id of 5438792800", at least for this product. Adding to the cart seems to use this process. This is United Kingdom specific as other regions have different product IDs.
> 
> 1. Visit `https://store.nvidia.com/store/nvidia/SessionToken?format=json&locale=en_us&apiKey=9485fa7b159e42edb08a83bde0d83dia` which will return your current `access_token`.
> 2. Visit `https://api.digitalriver.com/v1/shoppers/me/carts/active/line-items?format=json&method=post&productId=5438792800&quantity=1&token={the previous access_token}`
> 3. Visit `https://api.digitalriver.com/v1/shoppers/me/carts/active/web-checkout?productId=5438792800&token={the previous access_token}`

It's possible they changed their productID on DigitalRiver, if you find the new one let me know or submit the change to the README.md please.

**Comment by forestlovewood** [comment]
@ianmarmour I've searched DigitalRiver pretty thoroughly, I'm suspicious that they've actually disabled/deactivated the product. The product list that we've been using as a source is likely cached, but whenever I've tried any requests against it that wouldn't have been it says the product does not exist. This extends to searching for the product reference (`900-1G133-2530-00`), which is on the packaging and will not be changing – it doesn't show up when searched for in DigitalRiver.

**Comment by ianmarmour** [comment]
Yeah the product reference isn't stored in DigitalRiver, last night I was able to query digital river similarly to you and there were 3 listings for the 3080 has the SKU stopped working since yesterday evening?

**Comment by forestlovewood** [comment]
@ianmarmour The listings only seemed to stop working several hours ago, although it's unclear because the testing was getting more thorough at the same time.

**Comment by mychaelhoward** [comment]
just got back from work and it seems its been working while ive been gone. its working rn for me

**Comment by ianmarmour** [comment]
^^^ Can you post your configuration to help folks out.

**Comment by longgaminghours** [comment]
I still get this.


invalid character 'E' looking for beginning of value
Error getting SKU Information retrying...
invalid character 'E' looking for beginning of value
Error getting SKU Information retrying...

**Comment by ianmarmour** [comment]
Looks like I missed a location for 500 handling, going to push a fix for this now and create a new release later this afternoon that should resolve this. (Unless you're not seeing any good responses this is just a temporary issue on the API side)

**Comment by ianmarmour** [comment]
Please go grab the latest release, we stopped using the in-ru API in favor of calling digitalriver directly for everything, there's no longer stock information however the API is MUCH faster and more stable.
