### ISSUE TITLE
Halp im a noob

### ISSUE THREAD

**Issue by Rhylen** [ianmarmour/nvidia-clerk#111]
How do I (set DISCORD_WEBHOOK_URL=DISCORD_WEBHOOK_URL_HERE), do i have to edit the code myself? Do i make a batch file? Do i change it in the terminal? I'm on a mac which i dont normal use so I'm lost. 
I just need a rundown on how to set the variables.

Thanks hope that makes some sense.

**Comment by captainbraz** [comment]
In cmd just type “set DISCORD_WEBHOOK_URL=urlhere” (no quotes) and hit enter. Then run

**Comment by Rhylen** [comment]
rhylen@Rhylens-MBP ~ % set DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/######
rhylen@Rhylens-MBP ~ % ./downloads/nvidia-clerk-darwin -discord  -region=USA -model=3080
2020/09/25 14:18:28 Discord: DISCORD_WEBHOOK_URL Environment variable not found

This is what im getting, i know im doing something wrong on the first line.

**Comment by captainbraz** [comment]
Does the same webhook url work through windows? Wondering if it’s an issue with the env.

**Comment by Rhylen** [comment]
I would think so, i don't have a windows computer right now to test.

**Comment by ryan-robeson** [comment]
On macOS:

Either 

```DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/###### ./downloads/nvidia-clerk-darwin -discord -region=USA -model=3080```

 or

```
export DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/######
./downloads/nvidia-clerk-darwin -discord -region=USA -model=3080
```

should do the trick.

**Comment by redstone2019** [comment]
Yes, it's basically the same but with cmd @captainbraz 
`SET DISCORD_WEBHOOK_URL=https://discordapp.com/api/webhooks/#######`
`C:\Users\#####\downloads\nvidia-clerk-windows.exe -discord -region=USA -model=3080`

**Comment by redstone2019** [comment]
@Rhylen please close the issue if you got it now. Thank you.
