### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by Naterpin** [ianmarmour/nvidia-clerk#112]
I keep getting this error when I try to run any of the lines of code and don't know what to do.

"nvidia-clerk-windows.exe -region=USA -test
'nvidia-clerk-windows.exe' is not recognized as an internal or external command,operable program or batch file."

**Comment by captainbraz** [comment]
If you’re in cmd, navigate to the directory where the exe lives. I drop it on my desktop to make it easy. This way you can just open an elevated command prompt and cd Desktop then run it

**Comment by redstone2019** [comment]
@Naterpin please close the issue if you got it now. Thank you.
