### ISSUE TITLE
Question: 3070?

### ISSUE THREAD

**Issue by chronicsynergy** [ianmarmour/nvidia-clerk#114]
Sorry if this has been asked before, but when will support for the 3070 come? Will it be **before the launch** so I can actually get one when it comes out? If not, then I don't know how I'm gonna get one, the 3070 will probably be the worst of the 3 because it's the cheapest and half the people who couldn't get a 3080 will probably be going for it. Again, sorry if this has been asked before.

**Comment by redstone2019** [comment]
#43

**Comment by redstone2019** [comment]
@chronicsynergy #43
