### ISSUE TITLE
API connection issue

### ISSUE THREAD

**Issue by m9x3mos** [ianmarmour/nvidia-clerk#115]
App just started giving me these errors after unexpected end of JSON input messages.
2020/09/25 17:11:04 Get "https://api-prod.nvidia.com/direct-sales-shop/DR/products/en_us/USD/5438481600": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by ianmarmour** [comment]
Closing this in favor of the other already open issue #116 please track there
