### ISSUE TITLE
Cannot start the bot

### ISSUE THREAD

**Issue by EntropyGit-zz** [ianmarmour/nvidia-clerk#118]
So basically the bot has been running fine for hours but now I am getting an error in cmd. 

I navigate to the .exe dir and paste the following command: `nvidia-clerk-windows.exe -region=GBR -model=3080`

And then cmd spits out the following error:

`2020/09/25 23:34:05 invalid character '<' looking for beginning of value
2020/09/25 23:34:05 Error getting session token from NVIDIA retrying...`

**Comment by ianmarmour** [comment]
See #116 closing, track updates there.
