### ISSUE TITLE
error getting session token from nvidia

### ISSUE THREAD

**Issue by Markw27348** [ianmarmour/nvidia-clerk#119]
error getting session token from nvidia every time

**Comment by lifewater** [comment]
Same problem:
[root@server scripts]# ./nvidia-clerk-linux -region=USA -test
2020/09/25 19:52:13 invalid character '<' looking for beginning of value
2020/09/25 19:52:13 Error getting session token from NVIDIA retrying...

doesnt work for any region.  tried on mulitple machines.  I have the latest version as well.

It was working for a short while, but when I came back it stopped working alltogether.

**Comment by hymer08** [comment]
Someone in a different forums mentioned that nvidia was under maintenance? if that's true then it explains why it stopped working

**Comment by Colorblindninja** [comment]
Yeah the add to cart link takes you to a maintenance page, and the direct sales link gives 504 error right now.

https://store.nvidia.com/store?Action=AddItemToRequisition&SiteID=nvidia&Locale=en_US&productID=5438481700&quantity=1

https://api-prod.nvidia.com/direct-sales-shop/DR/products/en_us/usd/5438481700

**Comment by nasell** [comment]
Is there some code that could handle this error and keep running, maybe reduce the check-in frequency, and then resume when it's back up? Otherwise the app quits and we're left restarting it constantly...

**Comment by redstone2019** [comment]
you could try the bat I posted on the discord server https://discordapp.com/channels/759183179717541920/759229482715578378/759235891813285929 https://discord.gg/bHVqB4

**Comment by Patrity** [comment]
Same issue, can confirm nvidia appears to be down.

**Comment by vic18t** [comment]
Yeah nvidia is down to fix a data leak

**Comment by CPYY** [comment]
> Yeah nvidia is down to fix a data leak

I don't think nvidia is down since nvidia snatcher is working fine but its slower.

**Comment by callrua** [comment]
The Nvidia API is back now, if you want to try another test.

**Comment by gamingarena23** [comment]
It's working now! Finally!

**Comment by redstone2019** [comment]
@Markw27348 Please close, this issue has resolved itself.
