### ISSUE TITLE
CTD on startup

### ISSUE THREAD

**Issue by ProfeSSD** [ianmarmour/nvidia-clerk#120]
The command window immediately crashes when I start the process, is this a user error and I'm running the bot wrong, or is this a piece of malignant code?

**Comment by redstone2019** [comment]
how are you running it?

**Comment by hymer08** [comment]
Bot isnt working yet due to nvidia site issues anyway

**Comment by redstone2019** [comment]
yeah but it shouldn't be crashing instantly

**Comment by ProfeSSD** [comment]
I'm running is as it's own process, since I idk how to manually start it through the command prompt

**Comment by redstone2019** [comment]
yeah you need to run it manually for cmd or it crashes instantly

**Comment by redstone2019** [comment]
where is it on your pc? @ProfeSSD

**Comment by ProfeSSD** [comment]
standard downloads folder

**Comment by redstone2019** [comment]
username?

**Comment by ProfeSSD** [comment]
yee

**Comment by redstone2019** [comment]
so open a cmd window and run this
`C:\users\yee\downloads\nvidia-clerk-windows.exe -region=USA -model=3080`

**Comment by redstone2019** [comment]
let me know if it works

**Comment by ProfeSSD** [comment]
Imma do that

**Comment by redstone2019** [comment]
did it work @ProfeSSD ?

**Comment by ProfeSSD** [comment]
not particularly, windows is having trouble finding the program

**Comment by redstone2019** [comment]
hm

**Comment by redstone2019** [comment]
error code?

**Comment by ProfeSSD** [comment]
none, thing just cant find it, doing admin runs now

**Comment by redstone2019** [comment]
can i see a screenshot?

**Comment by ProfeSSD** [comment]
wait

**Comment by ProfeSSD** [comment]
ah HA!

**Comment by redstone2019** [comment]
*Questioning Optimistically*

**Comment by ProfeSSD** [comment]
had to get it to start at system32. things all guuchi now

**Comment by redstone2019** [comment]
did you figure it out?

**Comment by redstone2019** [comment]
cool! can you close the issue please?

**Comment by redstone2019** [comment]
cool! can you close the issue, please? @ProfeSSD
