### ISSUE TITLE
Error adding card to checkout retrying...

### ISSUE THREAD

**Issue by illiffe** [ianmarmour/nvidia-clerk#123]
Nvidia seems to be up and running again but I can't seem to generate a link to the checkout?

**Comment by reubenprevost** [comment]
It worked for me. Tested just now with the 2060

**Comment by illiffe** [comment]
nvidia-clerk-windows.exe -region=USA -test

C:\Users\User>nvidia-clerk-windows.exe -region=USA -test

2020/09/26 17:58:14 Product ID: 5438481700
2020/09/26 17:58:14 Product Name: NVIDIA GEFORCE RTX 3080 - US
2020/09/26 17:58:14 Product Locale: en_us
2020/09/26 17:58:14 Product Status: PRODUCT_INVENTORY_OUT_OF_STOCK

2020/09/26 17:58:15 Error adding card to checkout retrying...

Not sure what I'm doing wrong?

**Comment by reubenprevost** [comment]
The problem is the 3080 is out of stock. 

use these flags:
nvidia-clerk-windows.exe -model=2060 -test -region=USA

You don't really need to use the test flag. It's only for testing, but if the product is out of stock, then it won't work.

**Comment by illiffe** [comment]
Appreciated thank you.
