### ISSUE TITLE
-remote command not automatically adding item to cart

### ISSUE THREAD

**Issue by shaunster80** [ianmarmour/nvidia-clerk#125]
Testing with a 2060 the -remote command doesn't add the item automatically to my cart anymore. A link is sent to my phone but after clicking it takes me to an empty cart page. Testing the clerk without the -remote command on my computer adds the 2060 to my cart as intended.

**Comment by Qerlak** [comment]
What region / version of clerk / phone OS / notification delivery system are you using? I'm using an iPhone XS Max on iOS 14, discord notifications, and the -remote tag with the 2060 works, adding card directly to my cart on my phone or computer.

**Comment by reubenprevost** [comment]
If you are on android, you would need to turn off web link previews in your messenger settings.

**Comment by shaunster80** [comment]
> What region / version of clerk / phone OS / notification delivery system are you using? I'm using an iPhone XS Max on iOS 14, discord notifications, and the -remote tag with the 2060 works, adding card directly to my cart on my phone or computer.

Latest version of Clerk (I've tried older versions too), IPhone X with IOS 14, USA region, Twilio SMS service

Running command; nvidia-clerk-windows.exe -region=USA -model=2060 -sms -remote

**Comment by thenearl** [comment]
The link works for me on Android if my default browser is set to Samsung, but not Chrome

**Comment by shaunster80** [comment]
> The link works for me on Android if my default browser is set to Samsung, but not Chrome

Hmm, I'm using safari on IOS. But I swear it was working a couple days ago.

**Comment by shaunster80** [comment]
![Remote](https://user-images.githubusercontent.com/71941450/94348336-18b57300-fff0-11ea-966f-81ec47009098.jpg)

**Comment by ianmarmour** [comment]
@shaunster80 You need to turn off link previewing

https://osxdaily.com/2018/08/02/disable-url-link-previews-messages-ios-mac/

^^^ This is one way we could do it, but I believe there's a way to do it IOS wide (it doesn't do it on my ios 14 device)

**Comment by shaunster80** [comment]
> @shaunster80 You need to turn off link previewing
> 
> https://osxdaily.com/2018/08/02/disable-url-link-previews-messages-ios-mac/
> 
> ^^^ This is one way we could do it, but I believe there's a way to do it IOS wide (it doesn't do it on my ios 14 device)

Ahh.. ok I think I'm getting somewhere now thanks Ian and everyone. So I can get the item into my cart now but it looks like I can only use the link once. If I remove the item and then try clicking the link again it doesn't add the item again. Seems to be a one shot deal per link. This is fine though, I'll only ever need one shot.

**Comment by ianmarmour** [comment]
Yep I just updated the URL to automatically include periods to escape it on IOS.

**Comment by ianmarmour** [comment]
Resolved in the latest release.
