### ISSUE TITLE
Arm binaries not able to be executed on Raspberry Pi

### ISSUE THREAD

**Issue by MadEngineer75** [ianmarmour/nvidia-clerk#126]
The arm executable you provided is not able to be executed on my Pi. Upon investigation I found out the the Go compiler support different version of the arm architecture(v5, v6, and v7). To specify the arm version to build for you just add GOARM=(5, 6, or 7) to the build variables.

Weirdly enough my Raspberry Pi works with all arm versions when I specify a specific arm version to build for. But, when I don't specify an arm version my Pi doesn't want to execute the binary.

So I suggest you build for arm v5, since it seems to work on newer arm architectures, if you don't want to build for every arm version.

Thanks for all your effort

**Comment by redstone2019** [comment]
#124 Please Close

**Comment by redstone2019** [comment]
#124 Please Close @MadScientist75

**Comment by MadEngineer75** [comment]
> 
> 
> #124 Please Close @MadScientist75

This is a follow up to that. The binaries provided by the release aren't able to be executed on my Raspberry Pi

**Comment by redstone2019** [comment]
can you add your knowledge over there to have only 1 issue about this topic?

**Comment by MadEngineer75** [comment]
Sorry, thought the issue referenced was my request for the arm binaries. I just realized it was different. I'll close this and add my knowledge on the other issue
