### ISSUE TITLE
Alarming

### ISSUE THREAD

**Issue by Ditkafan85** [ianmarmour/nvidia-clerk#128]
Have you considered setting an audible alarm to alert the user if they are not looking at this computer when stock becomes available?

**Comment by kevnwong** [comment]
I second your suggestion.

**Comment by ianmarmour** [comment]
I have considered it and still am, if you setup notifications without remote you can get this functionality too. 

The only issue with doing this is as far as I know there's no library that does cross platform sound processing (we have users on basically every operating system so this is a major consideration for me)

**Comment by Ditkafan85** [comment]
Fair enough.  -sms functionality gets us 95% of the way there. Thanks for your consideration and for keeping this functional for those of us trying to get our hands on a 30 series card :)

**Comment by ianmarmour** [comment]
@Ditkafan85 See the latest release, I've added a -desktop flag that uses the windows/mac/linux notification centers to send a visual and auditory alert.

**Comment by kevnwong** [comment]
I have just tested the new notification feature on the RTX 2060 and it works like a charm.
