### ISSUE TITLE
Android /ios support

### ISSUE THREAD

**Issue by Moortu** [ianmarmour/nvidia-clerk#129]
I know it is far fetched.
But you can add make an app out of it
https://github.com/golang/go/wiki/Mobile

**Comment by redstone2019** [comment]
In the meantime you can use -sms to get phone notifications.

**Comment by Nariakira123** [comment]
What's the syntax for using SMS?

**Comment by redstone2019** [comment]
https://github.com/ianmarmour/nvidia-clerk#sms-notifications
`set TWILIO_ACCOUNT_SID=YOUR_TWILIO_ACCOUNT_SID_HERE`
`set TWILIO_TOKEN=YOUR_TWILIO_TOKEN_HERE`
`set TWILIO_SOURCE_NUMBER=YOUR_TWILIO_SERVICE_NUMBER_HERE`
`set TWILIO_DESTINATION_NUMBER=YOUR_DESITNATION_NUMBER_FOR_NOTIFICATIONS_HERE`
`nvidia-clerk-windows.exe -sms -region=REGION_CODE_HERE -model=3080`

**Comment by ianmarmour** [comment]
This is not going to happen sorry, adding support for this running on iOS and Android is non-trivial and would require a large amount of effort with minimal users. I'm sorry about that, please feel free to use our SMS support functionality to support these two device types!
