### ISSUE TITLE
Error getting SKU information retrying... invalidcharacter '<' looking for beginning of value

### ISSUE THREAD

**Issue by Vanguard1138** [ianmarmour/nvidia-clerk#13]
This is using en_GB, UK SKU, gbp - Occasionally there will be a successful ping but it's mostly putting out the above at this point

**Comment by callrua** [comment]
It looks like one of the endpoints are down, I'm experiencing the same with the same env.

Others reporting the same thing, eg #11

**Comment by Vanguard1138** [comment]
Makes sense, thanks! I can only imagine it's going to get worse on the run up to 2pm

**Comment by nefar10us** [comment]
> ... it's going to get worse on the run up to 2pm

What's happening at 2PM? And in what timezone?

**Comment by Vanguard1138** [comment]
It's when the cards were first due to go live in the UK on Thursday so when we're predicting they'll release new stock. It's not based on anything.

**Comment by nasell** [comment]
Unfortunately, it's also having the issue on en_us

**Comment by Vanguard1138** [comment]
It looks like GB may be coming back up.

**Comment by nasell** [comment]
Same with US - it's intermittent, but working!

**Comment by longgaminghours** [comment]
I'm getting the same error.

**Comment by ianmarmour** [comment]
These error's are caused by intermittent timeouts, I'm going to close out this issue for now. If you're still receiving these request but not intermittently feel free to open again/another.
