### ISSUE TITLE
Wrong locale for Norwegian

### ISSUE THREAD

**Issue by labanx** [ianmarmour/nvidia-clerk#130]
Seems like your using the wrong locales for Norwegian.

Locale: no_NO
Should be 
nb_NO

Ref https://www.nvidia.com/nb-no/

**Comment by labanx** [comment]
Seems also be crashing if test using NOR.

```
nv-clerk@terra:~$ ./nvidia-clerk-linux -sms -test -model=2060 -region=NOR
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x682d3f]

goroutine 1 [running]:
main.main()
        /home/runner/work/nvidia-clerk/nvidia-clerk/main.go:65 +0x5bf
```

While US works fine
```
nv-clerk@terra:~$ ./nvidia-clerk-linux -sms -test -model=2060
2020/09/27 10:46:39 Product ID: 5379432500
2020/09/27 10:46:39 Product Name: NVIDIA GEFORCE RTX 2060 SUPER NEW - US
2020/09/27 10:46:39 Product Locale: en_us
2020/09/27 10:46:39 Product Status: PRODUCT_INVENTORY_IN_STOCK

2020/09/27 10:46:41 Error attempting to open browser.exec: "xdg-open": executable file not found in $PATH
```

**Comment by redstone2019** [comment]
You are correct, that locale is wrong.

**Comment by redstone2019** [comment]
Ok so @labanx as it turns out, I'm very tired and didn't notice that you were using -model=2060 which is only supported in the USA and will throw out that error if you try another region.
![image](https://user-images.githubusercontent.com/50508889/94371011-1ca4cc00-00a8-11eb-9b07-800bc35dfd69.png)
