### ISSUE TITLE
-Region=CAN can't find product info on 3080 or 3090

### ISSUE THREAD

**Issue by redstone2019** [ianmarmour/nvidia-clerk#132]
![image](https://user-images.githubusercontent.com/50508889/94371326-8920ca80-00aa-11eb-8d62-2395eaba20f2.png)
`nvidia-clerk-windows.exe -region=CAN -model=3080`
`nvidia-clerk-windows.exe -region=CAN -model=3090`

**Comment by ianmarmour** [comment]
Solved in latest release.
