### ISSUE TITLE
Error adding card to checkout retrying...

### ISSUE THREAD

**Issue by gamingarena23** [ianmarmour/nvidia-clerk#136]
It wont add the card  to checkout anymore.
I tried with -model=2060 it shows in stock and then it spits the error:  "Error adding card to checkout retrying..."

I tired with both newest 3.7.7 and older 3.6 versions which worked last night both giving errors now!

**Comment by Laterallus** [comment]
I can confirm - same here.

![image](https://user-images.githubusercontent.com/71896704/94377776-0d4a7080-00f2-11eb-96dd-26838f21bc55.png)

Thanks for all of your hard work on this Ian!

**Comment by gamingarena23** [comment]
new error now:
"Get "https://api-prod.nvidia.com/direct-sales-shop/DR/products/en_us/USD/5438481600": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"

EDIT: everything back to normal it works now!

**Comment by redstone2019** [comment]
#123
