### ISSUE TITLE
Product Inventory

### ISSUE THREAD

**Issue by javitab** [ianmarmour/nvidia-clerk#14]
Does the Product Inventory response indicate the amount of current "in-warehouse' inventory that is waiting to be released for purchase? I've seen some people reporting a number of "2" as where I've consistently been seeing 363. Does that mean that 363 cards are ready to go pending Nvidia changing the status to "in stock"?

**Comment by longgaminghours** [comment]
No idea

**Comment by ianmarmour** [comment]
As far as I know yes 363 indicates the in-warehouse inventory. Folks who see 2 or 1 are in different regions, the US has by far the largest number of cards available.

**Comment by javitab** [comment]
Thanks! Just wanted to confirm. Thanks for doing god's work!
