### ISSUE TITLE
Error adding card to checkout retrying...

### ISSUE THREAD

**Issue by dexmar** [ianmarmour/nvidia-clerk#140]
Tried the new 3.7.8 with model=2060 test and I got that error.

When trying to add a 2060 from the browser the site hangs when I click 'Checkout' button so it's probably on nvidia's end, just sayin...

**Comment by redstone2019** [comment]
What error do you get?

**Comment by dexmar** [comment]
In the title:

Error adding card to checkout retrying...

**Comment by redstone2019** [comment]
yeah that's an Nvidia problem

**Comment by Hunter2205** [comment]
having the same issue when using the discord notifications.  eventually the browser pops up instead and adds to cart.

**Comment by redstone2019** [comment]
hm

**Comment by Hunter2205** [comment]
I ran this instance a few times and it did the same thing.  Restarted cmd.exe and seems to be working correctly now.  May have been something on my end?

**Comment by dexmar** [comment]
I am still getting the error on my Macbook and I am unable to add a 2060 manually with Chrome on the Mac as well. On Windows the script tries to add to the cart several times and finally succeeds. 

UPDATE: If I let it run long enough on the Mac it finally succeeds in adding to the cart and opening the browser

UPDATE2: Timed it, it takes up to 30 seconds to get the card successfully added to the cart.

**Comment by redstone2019** [comment]
So guys @dexmar @Hunter2205, whenever `Error adding card to checkout retrying...` happens assume it's NVIDIA's fault, and please don't make an issue on Github. You could ask on the discord though.

**Comment by dexmar** [comment]
Will do. Wasn't sure if it was a bug or not but I'll head on over to the Discord channel first.

Thanks!

**Comment by redstone2019** [comment]
yep

**Comment by redstone2019** [comment]
#136

**Comment by Hunter2205** [comment]
Will do.  Discord invite link expired the last I checked.
