### ISSUE TITLE
Your discord link is invalid

### ISSUE THREAD

**Issue by RedDrumJay** [ianmarmour/nvidia-clerk#142]
Title says it all. No way to get to your discord server for updates, etc. Link is invalid.

**Comment by redstone2019** [comment]
https://discord.com/invite/gTgJRz7 doesn't work?

**Comment by dexmar** [comment]
If you click on the link towards the bottom of the page, then you are clicking on an expired invite. If you click on chat at the top of the page then you are golden.

**Comment by RedDrumJay** [comment]
Yeah, the link at the bottom of the page is broken

**Comment by redstone2019** [comment]
ill fix that
