### ISSUE TITLE
Keep getting this error?

### ISSUE THREAD

**Issue by longgaminghours** [ianmarmour/nvidia-clerk#143]
2020/09/28 18:31:11 Get "https://api-prod.nvidia.com/direct-sales-shop/DR/products/en_us/USD/5438481700": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by angryboyscout** [comment]
I have the same issue, is the web API down?

**Comment by hymer08** [comment]
Nvidia is messing with the API probs. Distill bot isnt working on nvidia either

**Comment by redstone2019** [comment]
API is down

**Comment by redstone2019** [comment]
Just wait for it to come back

**Comment by Qerlak** [comment]
Yep this has happened before, Web API is down. It'll come back and start working eventually.

**Comment by BROKENMIND617** [comment]
How long is it usually down for? Is it ok to keep running .exe?

**Comment by penguinologist** [comment]
You can keep running it @BROKENMIND617. It's just polling against that. Won't get you any responses if it's down but won't hurt if you keep running it

**Comment by ianmarmour** [comment]
Nobody knows how long it will be down for, keep the tool running, maybe restart it once every 24 hours if you're concerned can't fix this so going to close out this issue.
