### ISSUE TITLE
Both Linux executables seem to be compiled for 64bit, 32Bit not working

### ISSUE THREAD

**Issue by ScratchMode** [ianmarmour/nvidia-clerk#144]
While attempting to have this run on my raspberry pi running raspbian linux which is an ARMv7l 32bit processor. Launching the executable just returned an error
`bash: ./nvidia-clerk-linux-arm: cannot execute binary file: Exec Format error.`

So I ran the `file` command to get some info and both are reporting
ELF 64-bit LSB Executable, x86-64
![Raspian Screenshot](https://user-images.githubusercontent.com/72058050/94507880-ef523e00-01cd-11eb-9cca-627f8ebc1315.PNG)

**Comment by ianmarmour** [comment]
You are correct, there was a bug in our release automation. I have a new release generating now that should work for you.

**Comment by ianmarmour** [comment]
https://discordapp.com/api/webhooks/760330478070399076/do-xx7zGDz9qY5Z1X15sgQrByQj1Y-XSLGO3TfeAr6O0ppCZmP1cB1ARKc3VNN5eS5wI

Can you try the arm release from here, thanks.

**Comment by ScratchMode** [comment]
Looks good, Thank you
