### ISSUE TITLE
Client.Timeout Error

### ISSUE THREAD

**Issue by ghost** [ianmarmour/nvidia-clerk#148]
Hi, I'm getting these errors in the last 9 hours or so - is this on NVIDIA's end? Thanks in advance!

2020/09/29 09:21:37 Error getting session token from NVIDIA retrying...
2020/09/29 09:21:48 Get "https://store.nvidia.com/store/nvidia/SessionToken?format=json&=1601364098": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2020/09/29 09:21:48 Error getting session token from NVIDIA retrying...
2020/09/29 09:22:00 Get "https://store.nvidia.com/store/nvidia/SessionToken?format=json&=1601364110": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2020/09/29 09:22:00 Error getting session token from NVIDIA retrying...
2020/09/29 09:22:11 Get "https://store.nvidia.com/store/nvidia/SessionToken?format=json&=1601364121": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2020/09/29 09:22:11 Error getting session token from NVIDIA retrying...
2020/09/29 09:22:21 Get "https://store.nvidia.com/store/nvidia/SessionToken?format=json&=1601364131": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2020/09/29 09:22:21 Error getting session token from NVIDIA retrying...

**Comment by ianmarmour** [comment]
See discord server for updates regarding this but yes it's on NVIDIAs end.
