### ISSUE TITLE
"unexpected end of JSON input"

### ISSUE THREAD

**Issue by staleh1** [ianmarmour/nvidia-clerk#149]
I have as others have noted, got a request timeout since the last 9-10 hours. I was able to get around that by downloading the src and increasing the http-client timeout. However, after doing so, I get this error message:
"unexpected end of JSON input"

I downloaded the source just now and I build and run on windows using new golang compiler.

**Comment by alopex92** [comment]
check if the nvidia store works in your browser. you probably will timeout in there too (check for known available products - like the titan rtx)...

either they are down, or we have been banned indivualy (but here, even my phone doesn't allow me to add to cart a known product). 

So it's probably not a "bug" on this side.

**Comment by alopex92** [comment]
something is happening accross the board : https://github.com/jef/nvidia-snatcher/issues/373

**Comment by staleh1** [comment]
Ok, there seems to be something (more than usually) odd with the Nvidia store too. It says out of stock, but that may be just a default..
