### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by Seth-G125** [ianmarmour/nvidia-clerk#15]
I am very new to coding in general and am unable to find the root of my problem. I cannot get the clerk executable to run through command prompt 

C:\Users\___>/nvidia-clerk-windows.exe
'/nvidia-clerk-windows.exe' is not recognized as an internal or external command,
operable program or batch file.

Is there something I am doing incorrectly?

**Comment by javitab** [comment]
Just drag the executable onto the window.

**Comment by longgaminghours** [comment]
Make sure you are also running CMD prompt as admin.

**Comment by Seth-G125** [comment]
Okay, thank you so much for the help

**Comment by Seth-G125** [comment]
Hm, am I still doing something wrong? 

- Opened Cmd Prompt as Admin
- Dragged the exe. file into the window
- set NVIDIA_CLERK_SKU=5438481700
- set TWILIO_DESTINATION_NUMBER=##########
- /nvidia-clerk-windows.exe -sms

**Comment by ianmarmour** [comment]
You also need to configure the twilio_api and twilio_account_sid if you intend on using sms notification, you can test your twilio setup with -test, if you don't know how to set this up you can run without SMS by removing the -sms

**Comment by Seth-G125** [comment]
Is dragging the executable onto the window supposed to have any visual feedback?

(Edit) Didn't run as admin and now I have visual feedback of the exec file location,etc
