### ISSUE TITLE
Getting this error after adding the exe file

### ISSUE THREAD

**Issue by FROOGLEPOWER** [ianmarmour/nvidia-clerk#152]
2020/09/29 09:42:54 Please choose one of the following supported regions: [CAN DNK USA IRL NOR NLD AUT LUX PRT CZE FRA ITA SWE BEL FIN DEU GBR POL ESP] by using -region=XXX
2020/09/29 09:42:54 : region unsupported

**Comment by redstone2019** [comment]
What command did you run?

**Comment by redstone2019** [comment]
@FROOGLEPOWER

**Comment by FROOGLEPOWER** [comment]
set NVIDIA_CLERK_SKU=5438481700

is that not correct? I've been using that one this whole time

**Comment by redstone2019** [comment]
No, we removed that a while ago now its
`nvidia-clerk-windows.exe -region=USA -model=3080`
or
`nvidia-clerk-windows.exe -region=CAN -model=3080`
whichever region you are
check readme.md for more info
