### ISSUE TITLE
Client.Timeout error

### ISSUE THREAD

**Issue by iklein53579** [ianmarmour/nvidia-clerk#155]
**Describe the bug**
When I run "nvidia-clerk-windows.exe --region=USA --model=3080", I get the following error:

Get "https://api-prod.nvidia.com/direct-sales-shop/DR/products/en_us/USD/5438481700": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

Any ideas on what might be doing wrong? Probably user error!

**Comment by redstone2019** [comment]
NVIDIA Problem with API
