### ISSUE TITLE
I'm still getting the timeout issue. Is Nvidia's website still broke? 

### ISSUE THREAD

**Issue by Naterpin** [ianmarmour/nvidia-clerk#156]
Get "https://api-prod.nvidia.com/direct-sales-shop/DR/products/en_us/USD/5438481700": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

I don't have the latest v3.7.9 release yet, because it doesn't open when I try to run it so I'm just using v3.7.7. Idk if that is the issue though.

**Comment by lessthankris** [comment]
Same, its been over 24 hours since its been able to make a connection for me.

**Comment by redstone2019** [comment]
No the version is not the issue, the api is still down. If you want to know without asking you can download and run this tool I made for this purpose at https://github.com/redstone2019/NVIDIA-API-Checker
