### ISSUE TITLE
Not sure what I'm doing wrong here but getting this error

### ISSUE THREAD

**Issue by FROOGLEPOWER** [ianmarmour/nvidia-clerk#161]
**CMD entry is:** 

nvidia-clerk-windows.exe -region=USA -model=3080

**getting this response:**

nvidia-clerk-windows.exe -region=USA -model=3080
'nvidia-clerk-windows.exe' is not recognized as an internal or external command,
operable program or batch file.

**Comment by redstone2019** [comment]
Where did you download the file to?

**Comment by glitch666** [comment]
Your cmd prompt needs to be in the same folder as the executable. If the executable is in your downloads folder type cd Downloads and it will change to that directory. Then you can run the command.

**Comment by FROOGLEPOWER** [comment]
That fixed it thanks
