### ISSUE TITLE
Opening to wrong pages?

### ISSUE THREAD

**Issue by chronicsynergy** [ianmarmour/nvidia-clerk#162]
Pretty simple, when I was testing the bot on the 2060 and 2070, 2060 opens the nvidia 20 series main page, and 2070 just opens nvidias main page, was something changed that's causing this, am I doing something wrong, or is it just bugged atm?

**Comment by redstone2019** [comment]
We had to change it because NVIDIA changed some stuff, so ftm, yeah it goes to those pages.

**Comment by chronicsynergy** [comment]
alright cool, hopefully fixed before 3070 launch, gotta get one haha
