### ISSUE TITLE
Bot Restart while away

### ISSUE THREAD

**Issue by ddamron88** [ianmarmour/nvidia-clerk#169]
I am away from home and saw that there was a drop that the bot picked up successfully. If there is a pattern, there could be another drop tonight, but I might not make it back from work in time to restart the bot.

Please add a feature to continue running the bot after a success. Perhaps it keeps checking for the item to be in stock, once the item goes out of stock again, it returns to normal, and only notifies you if it comes in stock after going back out of stock after a success. Thanks!

**Comment by redstone2019** [comment]
Just use a bat to loop it
If on Windows
```
:a
C:\Users\yourname\downloads\nvidia-clerk-windows.exe -region=USA -model=3080
GOTO :a
```

**Comment by ddamron88** [comment]
Will that notify me repeatedly for the minute things are in stock

**Comment by DougsHub** [comment]
My bot did NOT pick it up at all. I went through and checked the timestamps and it stayed OOS the entire time. Why would that be? Could it have anything to do with the fact that I'm tracking CAN and not USA? I was under the impression that they were the same store....

Realllly bummed out about this one. :(

**Comment by redstone2019** [comment]
> 
> 
> Will that notify me repeatedly for the minute things are in stock

Yes

**Comment by redstone2019** [comment]
@ddamron88 does that solve the problem?

**Comment by ddamron88** [comment]
I want to test it before I say yes. I am concerned that the frequent popups
would affect my ability to checkout, but it could work.

**Comment by redstone2019** [comment]
I know that code works because I use it. Closing, reopen if it has issues.

**Comment by ddamron88** [comment]
Kk
