### ISSUE TITLE
screen displays {"access token" .....

### ISSUE THREAD

**Issue by ibot4fun** [ianmarmour/nvidia-clerk#17]
Is it normal for Chrome to display the access token string? I can see the command prompt running through the inventory checker.

**Comment by ianmarmour** [comment]
This is the intended behavior yep it's working for you :)

**Comment by ianmarmour** [comment]
If you're unsure or want to test you can use the RTX 2060 SKU for your region but if you see the access token string and then the CLI window is updating with inventory it's functioning properly.
