### ISSUE TITLE
Configurable timeout time

### ISSUE THREAD

**Issue by mlodziaszka** [ianmarmour/nvidia-clerk#170]
Is it possible to add timeout variable?

`2020/10/01 22:16:26 Get "https://api-prod.nvidia.com/direct-sales-shop/DR/products/pl_pl/PLN/5438797700": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

It would allow to still track correctly when nvidia API is lagging.

**Comment by redstone2019** [comment]
its just down
