### ISSUE TITLE
Working earlier but now getting timeout

### ISSUE THREAD

**Issue by Getyourcardnow** [ianmarmour/nvidia-clerk#173]
It was working earlier and coming back from the server showing no stock but now there is a time out. I tried downloading the latest to no avail. Here is what I am getting from the CMD prompt. Same for shell. I think Nvidia is updating their API 

C:\Shell>nvidia-clerk-windows.exe -region=USA -model=3090
2020/10/01 18:27:55 Get "https://api-prod.nvidia.com/direct-sales-shop/DR/products/en_us/USD/5438481600": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by longgaminghours** [comment]
The API is down can't do anything about that.

**Comment by Droz23-Real** [comment]
> The API is down can't do anything about that.

AH that is what they meant earlier when they said they updated the API.  it actually down.  thanks

**Comment by Getyourcardnow** [comment]
That is what I thought. Thank you
