### ISSUE TITLE
Any way to fix this timeout error?

### ISSUE THREAD

**Issue by FROOGLEPOWER** [ianmarmour/nvidia-clerk#176]
Get "https://api-prod.nvidia.com/direct-sales-shop/DR/products/en_us/USD/5438481700": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by redstone2019** [comment]
No, this is the NVIDIA API being down

**Comment by FROOGLEPOWER** [comment]
Thanks
