### ISSUE TITLE
So is this no longer working?

### ISSUE THREAD

**Issue by FROOGLEPOWER** [ianmarmour/nvidia-clerk#178]
Looks like new issues are getting deleted and the tool hasn't been working for a couple of days. Is this no longer getting any support?

**Comment by glitch666** [comment]
It works, nvidias api is down, not an issue on this end.

**Comment by FROOGLEPOWER** [comment]
> It works, nvidias api is down, not an issue on this end.

Appreciate the response. Is it normal for their api to be down this long?

**Comment by redstone2019** [comment]
Yes, our dev team presumes they are doing it to keep bots behind the curve so they don't work when the API comes back online.

**Comment by redstone2019** [comment]
But whatever they change we will fix it
