### ISSUE TITLE
Panic runtime error

### ISSUE THREAD

**Issue by 8uN** [ianmarmour/nvidia-clerk#18]
does anyone know what this means? or is It working properly. 
Thanks for the help

**Comment by ianmarmour** [comment]
Can you post your configuration, the command you ran and your error output :) thanks

**Comment by 8uN** [comment]
I think this is it 
panic: runtime error: index out of range [0] with length 0
It's probably important to note that this is my first time ding anything related to coding

**Comment by hoodyFPS** [comment]
I also have the same issue

**Comment by hoodyFPS** [comment]
I run
set NVIDIA_CLERK_SKU=5438792300 
Z:\Downloads/nvidia-clerk-windows.exe

and recieve 
NVIDIA_CLERK_LOCALE unset defaulting locale to en_us.
NVIDIA_CLERK_CURRENCY unset defaulting currency to USD.
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.main()
        /home/runner/work/nvidia-clerk/nvidia-clerk/main.go:59 +0x785

Chrome opens in a tab with this code

{"access_token":"0ac25d414f09b4dd1db4698972d82ce53d794652ff500cdd9a182a24101aebab9232ccef6fe331fcd7b58a14cfe0938aa9bd3156f155ab1025eac7ff1231bb0f92a32f9ec4ecf882e4d9d3854d423b08","token_type":"bearer","expires_in":86114,"refresh_token":"0ac25d414f09b4dd1db4698972d82ce53d794652ff500cdd9a182a24101aebab00e01eeac5f851a239885d5a58ee7d1f679eb33b65ea90554fd1cb5b302b15324fb73cb9bf86653036e5c3dcc8b1fb5896e831cdf9964f90"}

**Comment by ianmarmour** [comment]
@8uN Do you have Google Chrome installed on your system?

**Comment by ianmarmour** [comment]
> I run
> set NVIDIA_CLERK_SKU=5438792300
> Z:\Downloads/nvidia-clerk-windows.exe
> 
> and recieve
> NVIDIA_CLERK_LOCALE unset defaulting locale to en_us.
> NVIDIA_CLERK_CURRENCY unset defaulting currency to USD.
> panic: runtime error: index out of range [0] with length 0
> 
> goroutine 1 [running]:
> main.main()
> /home/runner/work/nvidia-clerk/nvidia-clerk/main.go:59 +0x785
> 
> Chrome opens in a tab with this code
> 
> {"access_token":"0ac25d414f09b4dd1db4698972d82ce53d794652ff500cdd9a182a24101aebab9232ccef6fe331fcd7b58a14cfe0938aa9bd3156f155ab1025eac7ff1231bb0f92a32f9ec4ecf882e4d9d3854d423b08","token_type":"bearer","expires_in":86114,"refresh_token":"0ac25d414f09b4dd1db4698972d82ce53d794652ff500cdd9a182a24101aebab00e01eeac5f851a239885d5a58ee7d1f679eb33b65ea90554fd1cb5b302b15324fb73cb9bf86653036e5c3dcc8b1fb5896e831cdf9964f90"}

You're trying to use the German SKU with en_us and USD 

You'll need to set both the Locale to de_DE and currency to EUR for this SKU to work.

**Comment by longgaminghours** [comment]
@ianmarmour What is invalid character '<' looking for beginning of value
Error getting SKU Information retrying...
SKU Name: NVIDIA GEFORCE RTX 3080 - US
SKU Status: PRODUCT_INVENTORY_OUT_OF_STOCK
Product Inventory: 364 


This is what I keep getting.

**Comment by longgaminghours** [comment]
I am using this on Mac btw,

**Comment by ianmarmour** [comment]
Can you please pull down the latest release, and make sure you set the SKU to the one for Germany :) (see updated README for new usage instructions)

**Comment by longgaminghours** [comment]
@ianmarmour That worked no longer getting that error when I changed to Germany one.  Is there something wrong with the USA one?

**Comment by ianmarmour** [comment]
USA should work fine too, if you set your SKU to the US it should work as well.

**Comment by longgaminghours** [comment]
@ianmarmour I don't know what I'm doing wrong but this keeps saying this.  I am not very technically inclined to stuff like this so I apologize.

Error attempting to access URL: https://in-and-ru-store-api.uk-e1.cloudhub.io/DR/products/en_us/USD/5438481700
Error getting SKU Information retrying...

**Comment by 8uN** [comment]
> @8uN Do you have Google Chrome installed on your system?

yes, I have chrome. Sorry I did not reply earlier I had school

**Comment by 8uN** [comment]
> I run
> set NVIDIA_CLERK_SKU=5438792300
> Z:\Downloads/nvidia-clerk-windows.exe
> 
> and recieve
> NVIDIA_CLERK_LOCALE unset defaulting locale to en_us.
> NVIDIA_CLERK_CURRENCY unset defaulting currency to USD.
> panic: runtime error: index out of range [0] with length 0
> 
> goroutine 1 [running]:
> main.main()
> /home/runner/work/nvidia-clerk/nvidia-clerk/main.go:59 +0x785
> 
> Chrome opens in a tab with this code
> 
> {"access_token":"0ac25d414f09b4dd1db4698972d82ce53d794652ff500cdd9a182a24101aebab9232ccef6fe331fcd7b58a14cfe0938aa9bd3156f155ab1025eac7ff1231bb0f92a32f9ec4ecf882e4d9d3854d423b08","token_type":"bearer","expires_in":86114,"refresh_token":"0ac25d414f09b4dd1db4698972d82ce53d794652ff500cdd9a182a24101aebab00e01eeac5f851a239885d5a58ee7d1f679eb33b65ea90554fd1cb5b302b15324fb73cb9bf86653036e5c3dcc8b1fb5896e831cdf9964f90"}

this is the same thing I'm getting

**Comment by ianmarmour** [comment]
So if you want to use the US store not Germany you'll need to use this SKU,

5438481700

Also can you please download the latest release of the tool (it automatically updates currency and locale settings based on known SKU's and should help fix your problem)
