### ISSUE TITLE
Error attempting to access URL: https://api-prod.nvidia.com/direct-sales-shop/DR/products/en_us/USD/5438481700

### ISSUE THREAD

**Issue by MikeABentley** [ianmarmour/nvidia-clerk#180]
**Describe the bug**
Getting the following error when running the script: Error attempting to access URL: https://api-prod.nvidia.com/direct-sales-shop/DR/products/en_us/USD/5438481700

**To Reproduce**
1. Open Windows PowerShell
2. Start the tool 
3. You'll see the error on each ping of the NVidia API

**Expected behavior**
Successful response from NVidia API

**Comment by penguinologist** [comment]
probably the nvidia api being down

**Comment by redstone2019** [comment]
#179
