### ISSUE TITLE
Add Best Buy?

### ISSUE THREAD

**Issue by longgaminghours** [ianmarmour/nvidia-clerk#181]
Will you be adding Best Buy to this seeing as nvidia posted that they’re fixing their store and they won’t be selling their FE cards and in the meantime to buy from Best Buy? I linked the article below. 

https://www.nvidia.com/en-us/geforce/forums/geforce-graphics-cards/5/402196/nvidia-store-update-geforce-rtx-3080-and-rtx-3090-/

**Comment by redstone2019** [comment]
"...I don't have any intention of creating one..." Ian Armour via Discord referring to making a Best Buy bot.
