### ISSUE TITLE
It Is Unable to determine Google Chrome Install Location

### ISSUE THREAD

**Issue by brewski425** [ianmarmour/nvidia-clerk#19]
https://prnt.sc/ulbs5b
Not very tech-sabby apologies if this is a simple issue

IANMARMOUR thank you for doing god's work!

**Comment by longgaminghours** [comment]
Make sure Chrome is installed and set as default

**Comment by NickOttrando** [comment]
Relates to #4 - may need to support chrome path as env URL. It only checks in `C://` drive program files and user directory. @brewski425 where is your chrome exe located? You can find this by right clicking the icon in the start menu and selecting "open file location"

**Comment by brewski425** [comment]
> Make sure Chrome is installed and set as default

I double checked. Chrome is the default browser.

**Comment by ianmarmour** [comment]
@NickOttrando You want to add an environmental variable for custom chrome locations? I'm about to create a release with your changes from earlier as well.

**Comment by brewski425** [comment]
> Relates to #4 - may need to support chrome path as env URL. It only checks in `C://` drive program files and user directory. @brewski425 where is your chrome exe located? You can find this by right clicking the icon in the start menu and selecting "open file location"

it is under C:\Users\Me\AppData\Roaming\Microsoft\Windows\Start Menu\Programs

**Comment by NickOttrando** [comment]
> @NickOttrando You want to add an environmental variable for custom chrome locations? I'm about to create a release with your changes from earlier as well.

Yeah I can but I won't be able to get to it until later this evening probably.

**Comment by ianmarmour** [comment]
> > @NickOttrando You want to add an environmental variable for custom chrome locations? I'm about to create a release with your changes from earlier as well.
> 
> Yeah I can but I won't be able to get to it until later this evening probably.

That's fine, escaping the different strings for multiple operating systems is going to be a pain, your changes are released BTW.
