### ISSUE TITLE
Sweden SKU

### ISSUE THREAD

**Issue by thornierlamb** [ianmarmour/nvidia-clerk#20]
Swedens sku is 5438798100

Your cmd should look like this before dragging the exe in the window
![9440fd3c82a23610da2c04aee8f1c087](https://user-images.githubusercontent.com/47174189/93816833-59ac3100-fc58-11ea-8503-dcd1372e1d1c.png)

**Comment by ianmarmour** [comment]
Thanks so much for providing this information, I'm working on an official release for Sweden right now.

**Comment by ianmarmour** [comment]
Going to close this out now,

https://github.com/ianmarmour/nvidia-clerk/releases/tag/v0.8
