### ISSUE TITLE
SMS Issues

### ISSUE THREAD

**Issue by SixtyGig** [ianmarmour/nvidia-clerk#21]
I tried to enable the SMS responses, however I haven't been able to get it set up. 

I tried typing in the "config settings" (both manually and through a batch file) but command prompt wouldn't give me a response (no error or confirmation messages). So, I went into the source [config.go] and hard-coded my config codes (commenting out the automated setup lines). 

![image](https://user-images.githubusercontent.com/38166922/93821803-bdb50200-fc24-11ea-8d20-c76306ef804e.png)
_I blurred out my info for security reasons_

Now, I am getting nvidia stock results back on the debug console (yay), however, I don't see any SMS messages (even after running the test flag). 

Any thoughts on why this isn't working?

**Comment by ianmarmour** [comment]
So a few things can you download the latest release binary linked, and then provide the list of commands you're executing. Thanks!

**Comment by SixtyGig** [comment]
Apologies for the delay, been trying to keep up with all the builds. Nice progress by the way! :)

Question on the config: 
![image](https://user-images.githubusercontent.com/38166922/93833051-260fdd80-fc3d-11ea-8a14-c25a2f9b512a.png)

Is the "set" command supposed to be in a particular folder or just the base **nvidia-clerk-0.9** folder?

**Comment by SixtyGig** [comment]
Also, the **nvidia-clerk-windows** executable should be included in the Build Release, instead of a separate download.

**Comment by ianmarmour** [comment]
It doesn't matter where it's actually stored, as long as you use the same cmd.exe to run the nvidia-clerk command.

**Comment by ianmarmour** [comment]
Late update here but you don't need to specify the sku at all anymore just a region. 

Also just double check your Twilio export commands

**Comment by SixtyGig** [comment]
Okay, just to be 100% sure this is being completed correctly, I'm going to give a rundown of what steps I'm performing.
1. Download the latest release (currently **nvidia-clerk-1.5**) and the **nvidia-clerk-windows executable**.
2. Open **cmd.exe** in administrator mode _(for the sake of consistency, I am using my home directory C:\Users\NAME\)_.
3. I type in `nvidia-clerk-windows.exe -region=USA`
4. I get a successful run.
5. I then configure Twilio. Done.
6. I run an sms test [`nvidia-clerk-windows.exe -region=USA -sms -test`] and **it works** (whatever error I was having before was resolved in this or a previous build). Thanks for the assistance! 😄 

Now, the issue I'm having is the SMS sends to my phone...but the message **does not contain a link**
Here's a screenshot:
![image](https://user-images.githubusercontent.com/38166922/93911128-9feca900-fcc7-11ea-8a92-45058915213f.png)

**Comment by SixtyGig** [comment]
**Feature Request**
It would be really appreciative if the application's EXE file was also included in the source code's zip file :)

**Comment by ianmarmour** [comment]
> **Feature Request**
> It would be really appreciative if the application's EXE file was also included in the source code's zip file :)

Probably not going to go this route, it's not typical of any GitHub repositories to do this but feel free to checkout the latest builds section at any time for all the newest updates

**Comment by ianmarmour** [comment]
> Okay, just to be 100% sure this is being completed correctly, I'm going to give a rundown of what steps I'm performing.
> 
> 1. Download the latest release (currently **nvidia-clerk-1.5**) and the **nvidia-clerk-windows executable**.
> 2. Open **cmd.exe** in administrator mode _(for the sake of consistency, I am using my home directory C:\Users\NAME)_.
> 3. I type in `nvidia-clerk-windows.exe -region=USA`
> 4. I get a successful run.
> 5. I then configure Twilio. Done.
> 6. I run an sms test [`nvidia-clerk-windows.exe -region=USA -sms -test`] and **it works** (whatever error I was having before was resolved in this or a previous build). Thanks for the assistance! 😄
> 
> Now, the issue I'm having is the SMS sends to my phone...but the message **does not contain a link**
> Here's a screenshot:
> ![image](https://user-images.githubusercontent.com/38166922/93911128-9feca900-fcc7-11ea-8a92-45058915213f.png)

Probably not going to do a link, the bot will have already opened the checkout on your computer so you'll be able to login there. The checkout session requires browser based cookies so it's not simple to link you to the checkout on another device.

**Comment by ianmarmour** [comment]
Going to close this out for now as your main issue is solved, glad to see you got everything up and running.
