### ISSUE TITLE
Feature Request More Robust Logging

### ISSUE THREAD

**Issue by ianmarmour** [ianmarmour/nvidia-clerk#25]
Need to update all the logging in the application to log to a file so that users can post more in depth bug reports, this includes more data begin captured regarding response failures and log formatting should be consistent across the application.

E.X

nvidia-clerk-log.log

[log_type][process_id][timestamp] - log_message_content

**Comment by javitab** [comment]
Not sure if you would consider it part of this, but it would be nice if there was some sort of time stamp with each request printed to the console. If it's consistently been checking without errors, it can appear that it's hung despite continuing to hum along.

**Comment by ianmarmour** [comment]
That feature is already completed :) please see the latest release for the inclusion of timestamps :)

**Comment by ianmarmour** [comment]
Logging is better now closing this.
