### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by nefar10us** [ianmarmour/nvidia-clerk#28]
Getting this error upon trying to setup the bot:

`Get "http://localhost:9222/json/version": dial tcp [::1]:9222: connect: connection refused`

These are my commands that I previously entered:

```
% export NVIDIA_CLERK_SKU=5438481700
% export TWILIO_ACCOUNT_SID=[redacted]
% export TWILIO_TOKEN=[redacted]
% export TWILIO_SOURCE_NUMBER=[redacted]
% export TWILIO_DESTINATION_NUMBER=[redacted]
% chmod +x ./nvidia-clerk-darwin
% ./nvidia-clerk-darwin -sms
```

Running MacOS. Chrome is installed.
Script was working last time I ran which was v0.4

**Comment by ianmarmour** [comment]
I'm wondering if this is a permissions thing, nothing should have changed that would effect OSX users?

Do you see a chrome window opening when run,

% ./nvidia-clerk-darwin -sms

**Comment by dkasprick** [comment]
Same issue for me on linux but first time trying

`2020/09/21 18:56:38 Get "http://localhost:9222/json/version": dial tcp [::1]:9222: connect: connection refused`

**Comment by ianmarmour** [comment]
Try to sudo -E for the command (should use the environmental variables you set in your user account)

**Comment by dkasprick** [comment]
> Try to sudo -E for the command (should use the environmental variables you set in your user account)

Did do this, running in a VM though if it matters but made sure that I was running it as root

**Comment by nefar10us** [comment]
> I'm wondering if this is a permissions thing, nothing should have changed that would effect OSX users?
> 
> Do you see a chrome window opening when run,
> 
> % ./nvidia-clerk-darwin -sms

Not on the first time.
Second time worked like a charm, but still getting the odd issue as detailed in https://github.com/ianmarmour/nvidia-clerk/issues/29 (I understand this is the API - not the bot itself).

**Comment by ianmarmour** [comment]
Closing this out as it's now resolved please update to the latest release :)
