### ISSUE TITLE
Error attempting to access URL

### ISSUE THREAD

**Issue by FROOGLEPOWER** [ianmarmour/nvidia-clerk#29]
Bot is listing inventory but also showing this error

Error attempting to access URL: https://in-and-ru-store-api.uk-e1.cloudhub.io/DR/get-inventory/en_us/5438481700?format=json&expand=availablequantity
Error getting SKU Inventory retrying...

**Comment by javitab** [comment]
That's the API getting bogged down. That's not on the bot end, that's on the server.
