### ISSUE TITLE
Localhost failure?

### ISSUE THREAD

**Issue by jdkennedy45** [ianmarmour/nvidia-clerk#3]
> PS C:\Users\Jake\Downloads> ./nvidia-clerk-windows.exe
> 2020/09/20 23:12:25 Get "http://localhost:9222/json/version": dial tcp [::1]:9222: connectex: No connection could be made because the target machine actively refused it.

**Comment by ianmarmour** [comment]
Do you have chrome installed on your system? The latest changes to support the new auto checkout require that you have chrome installed, you should see a chrome browser launched whenever the application starts up and it needs to remain open.

**Comment by ianmarmour** [comment]
As a side note it also needs to be installed to your C drive,

"C:/Program Files (x86)/Google/Chrome/Application/chrome.exe"

**Comment by jdkennedy45** [comment]
Yeah, I do have it installed on my C drive. But it's at `C:\Program Files\Google\Chrome\Application\Chrome.exe`.

Google moved it off of x86 folder this year for new installs.

**Comment by ianmarmour** [comment]
Gotcha, I'm about to push a fix for this to determine multiple chrome locations. I'll update this issue when it's on the release page.

**Comment by ianmarmour** [comment]
Feel free to go pull down the latest release and let me know if that works for you :)

**Comment by jdkennedy45** [comment]
> Feel free to go pull down the latest release and let me know if that works for you :)

Actually I don't have anything to compile Go with, if you make another release I can test it.

**Comment by ianmarmour** [comment]
The latest release had the .exe file manually updated, you should be able to download that again to verify.

**Comment by jdkennedy45** [comment]
Nice. Works now.
