### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by Mitchell-T** [ianmarmour/nvidia-clerk#30]
after setting up the correct region and SKU number (5438796700, nl_nl, EUR) when i try to run it it opens chrome just fine but throws a fatal error

```
C:\Users\Mitchell\Desktop\Nvidia Clerk>nvidia-clerk-windows.exe
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.main()
        /home/runner/work/nvidia-clerk/nvidia-clerk/main.go:33 +0x625
```

any ideas what it could be?
SKU was found using the DigitalRiver API and postman

                "uri": "https://api.digitalriver.com/v1/shoppers/me/products/5438796700",
                "id": 5438796700,
                "displayName": "NVIDIA GEFORCE RTX 3080",
                "pricing": {
                    "uri": "https://api.digitalriver.com/v1/shoppers/me/products/5438796700/pricing",
                    "formattedListPrice": "719,00 €",
                    "formattedSalePriceWithQuantity": "719,00 €"
                }

**Comment by ianmarmour** [comment]
Can you post me the commands you used to configure the application?

**Comment by Mitchell-T** [comment]
```
set NVIDIA_CLERK_SKU=5438796700
set NVIDIA_CLERK_LOCALE=nl_NL (tried both nl_nl and nl_NL)
set NVIDIA_CLERK_CURRENCY=EUR
```

also checked it manually on https://in-and-ru-store-api.uk-e1.cloudhub.io/DR/products/nl_NL/EUR/5438796700 and it seems to be giving a valid response

**Comment by ianmarmour** [comment]
Which release are you running? Can you try and pull down the latest and post if there's still an error?

**Comment by Mitchell-T** [comment]
```
C:\Users\mitch\Desktop\Nvidia Clerk>nvidia-clerk-windows.exe
SKU Name: NVIDIA GEFORCE RTX 3080 - NL
SKU Status: PRODUCT_INVENTORY_OUT_OF_STOCK
Product Inventory: 1

SKU Name: NVIDIA GEFORCE RTX 3080 - NL
SKU Status: PRODUCT_INVENTORY_OUT_OF_STOCK
Product Inventory: 1

SKU Name: NVIDIA GEFORCE RTX 3080 - NL
SKU Status: PRODUCT_INVENTORY_OUT_OF_STOCK
Product Inventory: 1
```

seems to be working now, thank you.
I will try to contribute in some way
