### ISSUE TITLE
Norway SKU

### ISSUE THREAD

**Issue by mutantsofthemonster** [ianmarmour/nvidia-clerk#33]
From https://in-and-ru-store-api.uk-e1.cloudhub.io/DR/products/no_no/NOK/5438797200

```
set NVIDIA_CLERK_SKU=5438797200
set NVIDIA_CLERK_LOCALE=no_NO
set NVIDIA_CLERK_CURRENCY=NOK
```

**Comment by ianmarmour** [comment]
New release has Norway added officially feel free to download it and try it out with -region
