### ISSUE TITLE
Rate limit exceeded for API_KEY

### ISSUE THREAD

**Issue by Coveredz** [ianmarmour/nvidia-clerk#34]
After about 10 to 20 seconds running fine, I get the error `Rate limit exceeded for API_KEY`.
Polling might be too fast?
Region: FRA

**Comment by robertpan226** [comment]
Can confirm CAN also experiences the same problem.

**Comment by AlexandreSoteras** [comment]
Can confirm too.

I've tried delaying the polling randomly between 2-10sec, still getting the issue after a while.

**Comment by robertpan226** [comment]
Pretty sure there is no solution to this issue until we obtain a new API key. I’m assuming all the botters and people using similar programs all call using the same key.

**Comment by ianmarmour** [comment]
Interestingly I have yet to see this issue at all agains't EN US. (Been running the updated version of nvidia-clerk for 3+ hours)

**Comment by ianmarmour** [comment]
Can you post a screenshot/log file of the error you're getting as well?

**Comment by Coveredz** [comment]
Chrome instance shows
`Rate limit exceeded for API_KEY [9485fa7b159e42edb08a83bde0d83dia]`
Program returns
`2020/09/22 09:09:06 Unable to unmarshal inventory response data.`

The error seems to popup deterministically quite fast (never worked for longer than ~20s for me).

**Comment by ianmarmour** [comment]
Which release version are you using currently?

**Comment by Coveredz** [comment]
Well, I was using 1.2.
Just pulled 1.3, and it's been running for 2 minutes. You might have fixed it?

Edit: nevermind, the error just popped again after 3 minutes.

**Comment by forestlovewood** [comment]
Experienced the issue on 1.3 after running for 10 minutes.

**Comment by Altris001** [comment]
Hey, same error for me running 1.3
Also i have the exact same API key than Coveredz
That said, Discord notifications works perfectly with instant feedback

![Capture d’écran 2020-09-22 092200](https://user-images.githubusercontent.com/71692602/93853930-16cc7680-fcb5-11ea-910a-a60e2a1ef83f.png)

**Comment by ianmarmour** [comment]
Interesting, hypothetically if this is true if you start to get throttled you should eventually see some requests succeed again? Looking at other tooling that works similar to this they just attempt retries.

**Comment by JoeriDruyts** [comment]
The version from yesterday just retried I think. The version you published today stops and crashes. Maybe that is the "issue"?

**Comment by Altris001** [comment]
> Interesting, hypothetically if this is true if you start to get throttled you should eventually see some requests succeed again? Looking at other tooling that works similar to this they just attempt retries.

The program stop after the rate limit error occur, so you have to manually restart everything

**Comment by ianmarmour** [comment]
> The version from yesterday just retried I think. The version you published today stops and crashes. Maybe that is the "issue"?

100% Correct, I'll get a fix out for this shortly (I moved from JSON deserialization to XML and forgot to handle this error apparently).

**Comment by ianmarmour** [comment]
https://github.com/ianmarmour/nvidia-clerk/releases/tag/v1.5

Who want's to test (I tried the GBR stuff but still wasn't able to get it to trigger)

**Comment by Altris001** [comment]
I'm currently testing 1.5

**Comment by JoeriDruyts** [comment]
It's working for me. I got the error but it retried and continued correctly. Thanks!

**Comment by Altris001** [comment]
Auto refresh seems to work

![Capture d’écran 2020-09-22 100219](https://user-images.githubusercontent.com/71692602/93857353-bc361900-fcba-11ea-94d8-20fcc82f1921.png)

**Comment by ianmarmour** [comment]
Awesome I'll wait for @Coveredz to actually close out the issue to make sure he see's the new release.

**Comment by Altris001** [comment]
After 30 minutes it stopped refreshing, no error though, just stopped

![Capture d’écran 2020-09-22 103229](https://user-images.githubusercontent.com/71692602/93860149-edb0e380-fcbe-11ea-8713-3c1026aac00c.png)
![Capture d’écran 2020-09-22 103204](https://user-images.githubusercontent.com/71692602/93860152-ef7aa700-fcbe-11ea-8fae-192ebc97b830.png)

I'm trying again to see if this happen a second time

**Comment by Coveredz** [comment]
Can confirm all good now, cheers for the fast fix 👍 
@Altris001 Probably unlinked to this issue, mine didn't hang as of now. Suggest opening different ticket if it persists.

**Comment by ianmarmour** [comment]
Just a visual bug with cmd.exe probably, press enter to see terminal updates is the browser still refreshing if so it's all working properly still.

> After 30 minutes it stopped refreshing, no error though, just stopped
> 
> 
> 
> ![Capture d’écran 2020-09-22 103229](https://user-images.githubusercontent.com/71692602/93860149-edb0e380-fcbe-11ea-8713-3c1026aac00c.png)
> 
> ![Capture d’écran 2020-09-22 103204](https://user-images.githubusercontent.com/71692602/93860152-ef7aa700-fcbe-11ea-8fae-192ebc97b830.png)
> 
> 
> 
> I'm trying again to see if this happen a second time
