### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by vic18t** [ianmarmour/nvidia-clerk#35]
1. Time stamp for each order attempt so we know if the script stopped

2. Previous version showed number in stock. Can you bring this back?

**Comment by ianmarmour** [comment]
1. I can totally do this

2. This probably won't be something that I include again, it uses the in-ru API which I personally found to be incredibly unstable under load, the new DigitalRiver implementation is much more stable and is what NVIDIAs checkout uses to determine availability so it's more accurate.

**Comment by ianmarmour** [comment]
1 Is done, feel free to open another feature request regarding inventory and we can discuss further going to close this one out though,

https://github.com/ianmarmour/nvidia-clerk/releases/tag/v1.4

**Comment by vic18t** [comment]
1. Or instead of a timestamp, display attempt number.

2. Ah makes sense.

3. One more request, display the region and item name that it is attempting to order. It’s just much more reassuring to see that info, even though I did run -test.
