### ISSUE TITLE
Netherlands SKU

### ISSUE THREAD

**Issue by leondeklerk** [ianmarmour/nvidia-clerk#36]
Hi there could the Netherlands be added as well?

set NVIDIA_CLERK_SKU=5438796700
set NVIDIA_CLERK_LOCALE=nl_nl
set NVIDIA_CLERK_CURRENCY=EUR

Good job making this tool!

**Comment by ianmarmour** [comment]
About to release 1.4 with Netherlands support thanks for the info :)

**Comment by ianmarmour** [comment]
Done

https://github.com/ianmarmour/nvidia-clerk/releases/tag/v1.4
