### ISSUE TITLE
v1.5 - refresh stop after some times

### ISSUE THREAD

**Issue by Altris001** [ianmarmour/nvidia-clerk#39]
Hey, so i'm using v1.5 and at my first try of this version, the refresh stopped after 30min, no error though

![Capture d’écran 2020-09-22 103229](https://user-images.githubusercontent.com/71692602/93861743-4f724d00-fcc1-11ea-85a2-0e9b4f81f45f.png)
![Capture d’écran 2020-09-22 103204](https://user-images.githubusercontent.com/71692602/93861752-5305d400-fcc1-11ea-819e-09f501ccd41c.png)

Then i restarted for a 2nd try, and it stopped after 10min
![1](https://user-images.githubusercontent.com/71692602/93861965-a7a94f00-fcc1-11ea-879f-c1b7ad88b322.png)
![2](https://user-images.githubusercontent.com/71692602/93861974-aa0ba900-fcc1-11ea-82cb-97576d653160.png)

So i did a 3rd try, stopped after 12min
![3](https://user-images.githubusercontent.com/71692602/93863244-95301500-fcc3-11ea-8d25-69b0547ba8cb.png)
![4](https://user-images.githubusercontent.com/71692602/93863256-96f9d880-fcc3-11ea-9849-e08503f67302.png)

**Comment by ianmarmour** [comment]
Have you attempted to press return in the terminal and see if the terminal output unsticks? 

Also is the browser still refreshing?

**Comment by Altris001** [comment]
The browser stop refreshing as soon as the CMD stop, i'll try to use return when my 4th try stop (currently 13min in)

**Comment by Altris001** [comment]
17min for the 4th try, pressing return does nothing, browser stop refreshing the same second than CMD

![6](https://user-images.githubusercontent.com/71692602/93865279-65364100-fcc6-11ea-840e-dfee305fd973.png)
![5](https://user-images.githubusercontent.com/71692602/93865289-67989b00-fcc6-11ea-9217-edafdfa22735.png)

**Comment by ianmarmour** [comment]
This may be the first interesting bug, are you using Wifi? I'm wondering if something is disrupting the communication between Chrome and your Cmd.

What other processes are you using? What configuration and what operating system? Can you check task manager as the process runs too checking on memory utilization mostly.

**Comment by Altris001** [comment]
Ethernet on 100mbps connection, other process opened in background are Microsoft Edge (chromium version), Discord, Logitech G Hub for mouse and iCUE for keyboard, SoundBlaster Z for sound card, AMD Radeon for graphics card that's it

Specs : i5 6500 waiting for Zen 3
            R9 290X Tri-X
            8go DDR4
            SSD running latest version of W10

Memory usage : 

![Capture d’écran 2020-09-22 113904](https://user-images.githubusercontent.com/71692602/93866658-3caf4680-fcc8-11ea-8538-58ce10954dc2.png)

Currently running a 5th try, 12min in

**Comment by ianmarmour** [comment]
Are you just using the -region=FRA parameter or do you have any environmental variables set?

**Comment by Altris001** [comment]
Discord with a webhook link, when i run a discord test it instantly give me notification

**Comment by ianmarmour** [comment]
Going to have to hop off for the evening ideally we would enable preserve logging in the chrome developer tools menu of that browser and then upload that here for me to look through.

**Comment by Altris001** [comment]
Alright, i enabled "preserve log" from dev options, the program is running right now i'll update here if things goes well/wrong

Many many thanks for your help and your bot, you're a beast

**Comment by Altris001** [comment]
So the test lasted longer, 40min but same result after that, the browser/CMD stopped refreshing

**Comment by Coveredz** [comment]
Well, I can confirm I got the same issue after a few hours, and twice now.

**Comment by Altris001** [comment]
Little update, made a new test that stopped after a minute and here's what i got
![Capture d’écran 2020-09-22 125738](https://user-images.githubusercontent.com/71692602/93874134-32df1080-fcd3-11ea-9d96-88d258862fcd.png)

On previous test the browser page never stopped on API_KEY error but insted of the XML things without refreshing right after, is this a visual bug or the issue from 1.4 is not completely removed ?

**Comment by Altris001** [comment]
13min

![9](https://user-images.githubusercontent.com/71692602/93876046-6d967800-fcd6-11ea-9c70-d7b340c73948.png)
![10](https://user-images.githubusercontent.com/71692602/93876048-6ec7a500-fcd6-11ea-8d5c-5c377f122312.png)

Here's the HAR file from Chrome monitoring thing (had to zip-it in order to upload it here)
[api.digitalriver.com.zip](https://github.com/ianmarmour/nvidia-clerk/files/5261021/api.digitalriver.com.zip)

**Comment by Altris001** [comment]
Update : After the program stops, refreshing manually the browser seems to make it work again as the auto refresh begin and lines in CMD appears again
Though i don't know if the whole thing is actually running (putting a 3080 in cart when available) or it just "auto refresh for fake" and you have to close / re-open CMD and start all over from the beginning to make it actually work, especially the discord notification

**Comment by trentech** [comment]
I have the same issue. Stops refreshing after about a minute of running..

**Comment by rosherm** [comment]
Same issue here.

**Comment by rosherm** [comment]
> Same issue here.

I'm also using the discord webhook.

**Comment by trentech** [comment]
Can also confirm manually refreshing the page kicks back into gear..at least for a couple more minutes before dying again

**Comment by trentech** [comment]
Doing some testing I've noticed that if I keep chrome visible the tab up, it runs indefinitely, however if I start using Chrome and bring another tab in focus it quits. If I minimize Chrome sometimes it quits at a random time sometimes it does not.

**Comment by Altris001** [comment]
> Doing some testing I've noticed that if I keep chrome visible the tab up, it runs indefinitely, however if I start using Chrome and bring another tab in focus it quits. If I minimize Chrome sometimes it quits at a random time sometimes it does not.

Interesting

**Comment by trentech** [comment]
I take that back. I just had it quit when in focus too..There's no pattern as to when it stops. The only thing I've been able to consistently reproduce is opening a new tab and browsing the web, definitely causes it to quit.

**Comment by ianmarmour** [comment]
Oh to be clear the version of chrome that is launched by this program should not be used at the same time that the program is running. If you don't use this chrome but instead launch another for your dad to day browsing are you still encountering the same issues?

**Comment by ianmarmour** [comment]
I ask because I've had 1.5 running for 12 hours+ with no issues and plenty of other chrome windows open alongside it.

**Comment by Coveredz** [comment]
No, I can confirm it happens even without touching the application-launched chrome instance.
But it can take a while, I usually run 1h+ without issue.

**Comment by Altris001** [comment]
I use a different browser, Microsoft Edge and i don't touch at all the Chrome tab, in fact the tab is in a little corner of my screen so i can keep an eye on it and refresh it when it stop, same for CMD
Still got the bug

**Comment by ianmarmour** [comment]
Can one of you open up developer tools in the chrome being controlled by automated test software and click perserve log, once it freezes click the circled button in my link here and upload it to this ticket so I can look through the logs thanks!
![logging](https://user-images.githubusercontent.com/12246835/93915481-f56f8880-fcbc-11ea-993f-2e167baa083f.png)

**Comment by trentech** [comment]
https://pastebin.com/LhSEqxqu

**Comment by skyng22003** [comment]
https://pastebin.com/vsJDd2xz

**Comment by ianmarmour** [comment]
Looks like it's not on the network side at least, are you both using cmd.exe or powershell/other?

**Comment by skyng22003** [comment]
I'm using the windows terminal app, think it's a wrapper for power shell, refreshing the tab manually resumes the program

**Comment by trentech** [comment]
I'm using CMD. I can try PowerShell and see if I get a different result

**Comment by trentech** [comment]
Nope, same issue using PowerShell.

**Comment by arbyyyyh** [comment]
I seem to be having this issue as well. It starts fairly quickly though, after about a minute it stops consistently.

**Comment by javitab** [comment]
I am experiencing this issue as well. It appeared to be happier when I was using firefox to refresh bestbuy and evga instead of another chrome session but that bombed out too. I wish I could tell you which version number I upgraded from, but I have gone back to it (I believe it was immediately before chrome started reporting that it was being controlled by testing software if that helps). 

The variables that I have set are:

set NVIDIA_CLERK_SKU=5438481700
set TWILIO_ACCOUNT_SID={REDACTED}
set TWILIO_SERVICE_SID={REDACTED}
set TWILIO_TOKEN={REDACTED}
set TWILIO_SOURCE_NUMBER={REDACTED}
set TWILIO_DESTINATION_NUMBER={REDACTED}
set NVIDIA_CLERK_LOCALE=en_us
set NVIDIA_CLERK_CURRENCY=USD

**Comment by 8uN** [comment]
I have the problem

**Comment by ianmarmour** [comment]
https://github.com/ianmarmour/nvidia-clerk/releases/tag/v1.8

@Coveredz Can someone with this issue please test the latest release?

**Comment by ianmarmour** [comment]
@8uN Can you download the latest release and let me know if this fixes it for you.

**Comment by Mathametic** [comment]
@ianmarmour I just downloaded the latest version and am currently running it.

If it's of any use, I was running 1.5 for the past few hours and when I had my normal chrome browser open to do regular stuff like browse YouTube and such, it would keep stalling very often. When I closed my normal browser and had only the cmd and the clerk browser tab open, it kept running for a long time until I manually exited it just now to run v1.8

Edit: It ran for 11 minutes and 34 seconds, now it's stalling again.

**Comment by ianmarmour** [comment]
Could it be related to this,

https://github.com/microsoft/terminal/issues/2678

**Comment by Mathametic** [comment]
I'm not certain, but it pauses even when I don't interact with the console at all. Like I'm gaming right now and not tabbing out of the game and then when I do look at the console, I'll see that it stopped 20 minutes ago.

**Comment by javitab** [comment]
FWIW, I haven't run this on Windows Terminal once, I don't even have it on my machine. I've actually tried this on two different machines now, both of which it doesn't work on nor did 1.8 fix anything. I've spun up a xubuntu machine and so far it seems to be running fine on there.

EDIT: Also, when I was using the -delay argument, it seemed to not be effective, however, now that I'm running in Linux, I am the delay that I set with the argument. Not sure if this might be indicative of anything else, but I am definitely not using Windows Terminal or even clicking in and out of focus on the cmd window.

**Comment by ianmarmour** [comment]
The article actually mentions that it effects Windows and non windows alike, basically it just says if you click a terminal window it freezes the running application process.

Super strange, I'm actually running Windows myself and haven't had any of those issues, I'm glad you got it working on Linux I wonder what the difference could be between our environments... 

(Side note I also run 20+ tabs in Chrome with more then 4 instances of Chrome actually open and leave this thing running and have no issues)

**Comment by Altris001** [comment]
Latest release, not fixed
That said, letting us choosing between different RTX is good and well made

**Comment by Coveredz** [comment]
Yes I still have the problem too unfortunately, so I have to stay around and restart it every once in a while.

**Comment by trentech** [comment]
I can't be sure because it hasn't been running long, but I think adding a half second delay might have resolved this issue. Got about 15 minutes in so far which is the longest I've been able to get post 1.1 versions to run. I'm going to let it continue and report back.

**Comment by trentech** [comment]
Well...I got about a half hour before it died...so much for that.

**Comment by ianmarmour** [comment]
I wish I could re-produce this and I've been trying the only thing I notice is that clicking in the CMD can freeze execution of the program but outside of that I've been unable to reproduce this.

**Comment by trentech** [comment]
The clicking in the console window has been a long standing issue for years. This is not that. If that was the case, manually refreshing the page wouldn't make a difference which it does.

Since adding the delay If I let it run and leave everything visible and untouched everything seems to run without issue. I've currently had it running for 40 minutes and counting. If the windows happen to get minimized for too long however, it quits. So the delay does seem to be helping. It just seems very temperamental. Right now I have dedicated one of my monitors to just leave this running because every time it gets buried behind other windows or gets minimized it eventually quits.

**Comment by ianmarmour** [comment]
@trentech Think I might be on to something there, https://developers.google.com/web/updates/2017/03/background_tabs

That being said,

> Applications with real-time connections (WebSockets and WebRTC), to avoid closing these connections by timeout. The run-timers-once-a-second rule is still applied in these cases.

We should fall into this category....

I'm trying to reproduce this now with the same instructions you listed.

**Comment by ianmarmour** [comment]
@trentech I'm about to push a new build that may resolve this, I've swapped over to using completely headless browsing until we get to checkout, I'm hoping that the headless background process won't encounter whatever this issue is but I'm not confident yet.

**Comment by ianmarmour** [comment]
This should be solved now as we no longer use chrome, please download the latest release <3
