### ISSUE TITLE
Telegram not working "flag provided but not defined: -telegram"

### ISSUE THREAD

**Issue by jpdsc** [ianmarmour/nvidia-clerk#40]
Looks like the flag -telegram is not defined yet.
Can you check?

```
nvidia-clerk-windows.exe -telegram -test
flag provided but not defined: -telegram
Usage of nvidia-clerk-windows.exe:
  -discord
        Enable Discord webhook notifications for whenever SKU is in stock.
  -region string
        3 Letter region code (default "USA")
  -sms
        Enable SMS notifications for whenever SKU is in stock.
  -test
        Enable testing mode
  -twitter
        Enable Twitter Posts for whenever SKU is in stock.
```

**Comment by MauriceW67** [comment]
> Looks like the flag -telegram is not defined yet.
> Can you check?

I have the same issue (Windows version).

**Comment by JoeriDruyts** [comment]
Are you building yourself because the version with Telegram support hasn't been released yet?

**Comment by jpdsc** [comment]
If you can point where that is mentioned then I will close the issue. If I see it in the readme then I expect it is released.
If not, then point me where it states please

**Comment by JoeriDruyts** [comment]
![image](https://user-images.githubusercontent.com/6716569/93885247-3c24a900-fce4-11ea-8850-8a0eb0e0f246.png)

![image](https://user-images.githubusercontent.com/6716569/93885107-10092800-fce4-11ea-9f13-9cca962aa793.png)

Latest 1.5 release was build against 4015f39, which was before the merge of the telegram pull request.

**Comment by jpdsc** [comment]
You're right. Closing the issue then :-)
