### ISSUE TITLE
option to select the delay

### ISSUE THREAD

**Issue by Qualzz** [ianmarmour/nvidia-clerk#42]
It would be cool to have as launch argument a delay option. Seems like **500ms** may be way too fast. Had multiple "Api rate limites", and seems like it's somewhat heavy to let it run on the background.

**Comment by ianmarmour** [comment]
Seems like a very reasonable ask to me let me see what I can do :)

**Comment by ianmarmour** [comment]
https://github.com/ianmarmour/nvidia-clerk/releases/tag/v1.6

Closing this now that the feature was added :)

**Comment by Qualzz** [comment]
Perfect ! Thank you
