### ISSUE TITLE
Environment Variable unset

### ISSUE THREAD

**Issue by bdog4life** [ianmarmour/nvidia-clerk#44]
2020/09/22 07:02:31 NVIDIA_CLERK_SKU Environment Variable is unset, exiting.

What is it looking for?

**Comment by 8uN** [comment]
try to copy + paste this into CMD
NVIDIA_CLERK_SKU=5438481700
then are you dragging the .exe file into CMD

**Comment by warrengc3** [comment]
I am getting the same issue myself when trying to run the -sms -test
Running MacOS under zsh, I set both the variables of TWLIO_ACCOUNT_SID and TWILIO_ACCOUNT_SID as it appears the there is a typo in the code:

% ./nvidia-clerk-darwin -sms -test
2020/09/22 11:28:42 TWLIO_ACCOUNT_SID Environment Variable is unset, exiting.

Thoughts?

**Comment by bdog4life** [comment]
@8uN I launch CMD as admin, CD to the directory with the .exe and attempt to run it, it then errors out with my original post.

**Comment by 8uN** [comment]
> @8uN I launch CMD as admin, CD to the directory with the .exe and attempt to run it, it then errors out with my original post.

don't launch CMD as admin that's your problem

**Comment by ianmarmour** [comment]
You need to provide -region=WHATEVER_CODE when you run the program for the original OP

For warrengc3 make sure you have your environmental variables set for TWILIO_SMS see advanced configuration.

**Comment by warrengc3** [comment]
@ianmarmour First, thanks so much for your work here to help the gaming community!

I have set all the variables in my .zshrc files and confirmed they will echo as shown below:

![nvidia_env](https://user-images.githubusercontent.com/20330266/93927094-62e3df00-fce6-11ea-9224-256e731de92a.png)

**Comment by ianmarmour** [comment]
Interesting I'm wondering if this is a bug with using the environmental variables in ZSH, can you do me a favor as a test and go set them in your bash profile and then execute this command in ZSH and see if it still fails? (I'm wondering if bash environment is still used by golang)

As a temporary fix I would suggest executing in bash if it's possible

**Comment by warrengc3** [comment]
@ianmarmour So I added the variables to .bashrc and then tried to run in zsh and bash with the same error.

Is the typo causing us an issue?  It says TWLIO_ACCOUNT_SID and should be TWILIO_ACCOUNT_SID

![bashrc](https://user-images.githubusercontent.com/20330266/93937121-3b484300-fcf5-11ea-84a2-389cb3043641.png)

**Comment by ianmarmour** [comment]
Nope it shouldn't be,

https://github.com/ianmarmour/nvidia-clerk/blob/2771b28eb6118663ea796b0245f402d828ed5bbb/internal/config/config.go#L211-L213

That's just a typo in the log message but not the lookup.

Can you post the lines you added to your ZSH/BASHRC files?

**Comment by drod3763** [comment]
I was having the same issue, but I figured it out. Make sure you export the environment variables in your bashrc. As in:

```
export TWILIO_ACCOUNT_SID=
export TWILIO_TOKEN=
export TWILIO_SOURCE_NUMBER=
export TWILIO_DESTINATION_NUMBER=
```

**Comment by ngaugler** [comment]
@drod3763 is correct.  ZSH / BASH variables are not exported to the environment unless you explicitly export.  They are localized only for ZSH / BASH to use with other commands, such as for loops, if, etc.

**Comment by warrengc3** [comment]
Bingo! @drod3763 that was it!  I put the export in the .zshrc and bang worked right away!

@ianmarmour any thought to making this just a file so we don't have to rely on shell variables?

Do like an alert.conf file:

```
##### Twilio Config ######
enabled=true
TWILIO_ACCOUNT_SID=
TWILIO_TOKEN=
TWILIO_SOURCE_NUMBER=
TWILIO_DESTINATION_NUMBER=

##### Discord #######
enabled=false
......
```


Thoughts?

**Comment by penguinologist** [comment]
Just put the values in a wrapper script like mentioned in the FAQ?

**Comment by bdog4life** [comment]
I was able to put the set commands into a .bat file and it appears to run with one click.

**Comment by warrengc3** [comment]
Guys, I wrote a wrapper I called start_nv_clerk.sh which should work for Darwin and Linux.

Happy to include it in the project if you guys think it would be helpful.


```
#nvidia-clerk script wrapper
#!/bin/sh
#start_nv_clerk.sh
#by: warrengc3
#
#This is an example script to accept inputs and run the nvidia-clerk script.
#
#
# TWILIO - Here we setup our Twilio environment
set TWILIO_ACCOUNT_SID=YOUR_TWILIO_ACCOUNT_SID
set TWILIO_TOKEN=YOUR_TWILIO_TOKEN
set TWILIO_SOURCE_NUMBER=YOUR_TWILIO_PHONE_NR
set TWILIO_DESTINATION_NUMBER=THE_NUMBER_TO_WHICH_TO_SEND_THE_NOTIFICATIONS
#
# DISCORD
set DISCORD_WEBHOOK_URL=DISCORD_WEBHOOK_URL_HERE
#
# TWITTER
set TWITTER_CONSUMER_KEY=YOUR_TWITTER_CONSUMER_KEY_HERE
set TWITTER_CONSUMER_SECRET=YOUR_TWITTER_CONSUMER_SECRET_HERE
set TWITTER_ACCESS_TOKEN=YOUR_TWITTER_ACCESS_TOKEN_HERE
set TWITTER_ACCESS_SECRET=YOUR_TWITTER_ACCESS_SECRET_HERE
#
# TELEGRAM
#
set TELEGRAM_API_KEY=YOUR_TELEGRAM_API_KEY_HERE
set TELEGRAM_CHAT_ID=YOUR_TELEGRAM_CHAT_ID_HERE
#
#Now we ask the questions
echo "Welcome to nvidia clerk"
echo "What GPU do you seek? 3070,3080 or 3090:"
read model
echo "From where do you seek? AUT,BEL,CAN,CZE,DNK,FIN,FRA,DEU,USA,GBR,IRL,ITA,SWE,LUX,POL,PRT,ESP, NOR, NLD:"
read region
echo "Would you like to use messaging? sms,discord,telegram,twitter"
read messaging
echo "You have selected $model and $region and $messaging"
echo "Starting nvidia clerk now ....."
./nvidia-clerk-darwin $messaging -region=$region -model=$model
```

**Comment by Raphael-Lemercier** [comment]
@bdog4life Could you share the bat file please ?
