### ISSUE TITLE
exec: "google-chrome": executable file not found in %PATH%

### ISSUE THREAD

**Issue by NickOttrando** [ianmarmour/nvidia-clerk#46]
Haven't had time to look through what code has changed but I'm getting this error now when trying to run. 

I don't see anything in README about it?

> exec: "google-chrome": executable file not found in %PATH%

**Comment by ianmarmour** [comment]
Do you have Google Chrome installed on your path? We started using chromerd to execute and manage the running chrome instance, you can update your path to include google-chrome I suggest googling how to add to your path on Windows.

**Comment by NickOttrando** [comment]
> Do you have Google Chrome installed on your path? We started using chromerd to execute and manage the running chrome instance, you can update your path to include google-chrome I suggest googling how to add to your path on Windows.

I did not, may be worth it to update the README instructing users how to add it to their PATH. I just needed a new system variable named `google-chrome` with the value pointing to my chrome.exe location. Feel free to close issue as you see fit.

Thanks

**Comment by penguinologist** [comment]
The quick and dirty solution to this issue is to just reinstall chrome... it'll add it to the path and you'd be all set.

**Comment by NickOttrando** [comment]
> The quick and dirty solution to this issue is to just reinstall chrome... it'll add it to the path and you'd be all set.

I don't think so necessarily. I freshly installed Windows 10 and chrome a few days ago and the path was not added. It may depend how it was installed.

**Comment by penguinologist** [comment]
@ianmarmour @NickOttrando makes a pretty good point about a FAQ section in the readme. Some simple solutions would be great to add, or just point them to the issues here and let them search for their questions in here and post if they can't find what they're looking for.

**Comment by ianmarmour** [comment]
Totally onboard if anybody wants to go ahead and add that section to the readme :) working on debugging another issue right now.

**Comment by penguinologist** [comment]
> Totally onboard if anybody wants to go ahead and add that section to the readme :) working on debugging another issue right now.

I'll work on it now :)

**Comment by ianmarmour** [comment]
> > Totally onboard if anybody wants to go ahead and add that section to the readme :) working on debugging another issue right now.
> 
> I'll work on it now :)

Nice!

**Comment by ianmarmour** [comment]
Change got merged going to close this now.
