### ISSUE TITLE
Different SKU

### ISSUE THREAD

**Issue by gamingarena23** [ianmarmour/nvidia-clerk#48]
How would you go by searching for different SKU like for upcoming 3090RTX?

**Comment by ianmarmour** [comment]
Currently there aren't published  SKU's for 3090 or 3070 cards, as soon as they become available I will add them to this application and support a parameter to indicate which one you would like to add to checkout.

**Comment by ianmarmour** [comment]
Closing for now.

**Comment by gamingarena23** [comment]
Thanks!
