### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by ghost** [ianmarmour/nvidia-clerk#52]
Is this what it's supposed to be doing now? Just grabbed the newer release and want to make sure.
![Screenshot 2020-09-22 18 01 41](https://user-images.githubusercontent.com/71635459/93942298-24f2b500-fcfe-11ea-8793-44effe449c17.png)

**Comment by joeymarc** [comment]
Yes

**Comment by ianmarmour** [comment]
Yep!

**Comment by ghost** [comment]
Thanks

**Comment by LOX311** [comment]
Mine is showing the same, im from germany so for german store ist working then or do i need to change some cfg to DEU?
