### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by Bungusbeefcake** [ianmarmour/nvidia-clerk#53]
As of 00:00GMT, the program has only returned Access Is Denied

**Comment by ianmarmour** [comment]
Download the latest release and can you please post the command you're running for the program

**Comment by tannguyen1024** [comment]
ian, will the new CAPTCHA affect this at all?

**Comment by LOX311** [comment]
Hey ianmarmour, 
I did nt want to open new issue so i ask here 

 im from germany so for german store ist working then or do i need to change some cfg to DEU?

https://ibb.co/xHNTVYy

**Comment by Bungusbeefcake** [comment]
Ian, 
![image](https://user-images.githubusercontent.com/71738251/93950388-47ef8a00-fd3b-11ea-98d6-598039718c65.png)

**Comment by Bungusbeefcake** [comment]
running cmd as admin on home network, no vpn or other gateway
At the same time I received the error on the actual Nvidia webpage and when the page resolved the buy now option seemed to be live but there was a blank window opened when trying to select the buy now option. This has now gon back to out of stock but the error on the program persists.

**Comment by ianmarmour** [comment]
@Bungusbeefcake That's a local error to your system you're either not running in an admin cmd prompt, have your rights restricted to execute programs, have an antivirus blocking it who knows you'll have to figure that out could be a myrid of things.

**Comment by ianmarmour** [comment]
> Hey ianmarmour,
> I did nt want to open new issue so i ask here
> 
> im from germany so for german store ist working then or do i need to change some cfg to DEU?
> 
> https://ibb.co/xHNTVYy

If you look at the readme you need to use nvidia-clerk-windows.exe -region=DEU (Your screenshot means the program is working though)

**Comment by ianmarmour** [comment]
> ian, will the new CAPTCHA affect this at all?

@tannguyen1024 Nope not as far as I can tell, the captcha is for the checkout process not the adding to cart.

**Comment by Bungusbeefcake** [comment]
> @Bungusbeefcake That's a local error to your system you're either not running in an admin cmd prompt, have your rights restricted to execute programs, have an antivirus blocking it who knows you'll have to figure that out could be a myrid of things.

Hi Ian, 

Can you verify that it's working for you?

I've full admin on, the cmd is running as admin, anti-virus and firewall disabled. It was running for me seamlessly all today but stopped then at midnight, as I said at the same time I had an access is denied on the nvidia webpage

**Comment by penguinologist** [comment]
I was able to reproduce the same error ("Access Denied") but it turned out that my AV just moved the file to the Virus Chest (Avast you filthy scoundrel...). @Bungusbeefcake check to see if the file also gets removed from the directory where you're running from. It did that for me and that's what had me checking for errors and that's when I noticed my AV had a notification pending.

**Comment by ianmarmour** [comment]
@Bungusbeefcake I'm running it right now everything's fine on my end.

**Comment by LOX311** [comment]
> > Hey ianmarmour,
> > I did nt want to open new issue so i ask here
> > im from germany so for german store ist working then or do i need to change some cfg to DEU?
> > https://ibb.co/xHNTVYy
> 
> If you look at the readme you need to use nvidia-clerk-windows.exe -region=DEU (Your screenshot means the program is working though)

Yea i saw that in the readme but i didnt change anything and the program seems to work, what i dont know tho is it checking the us store or de store?

Do i change that in the readme file or else where?

Also i'd like to donate you some € through paypal is that possible here?
my first time on this website.

**Comment by ianmarmour** [comment]
If you're going to donate anywhere please donate here :)

https://donate.code.org/campaign/support-computer-science-education/c172233



You need to set the DEU region otherwise it will run against USA by default.

**Comment by LOX311** [comment]
> If you're going to donate anywhere please donate here :)
> 
> https://donate.code.org/campaign/support-computer-science-education/c172233
> 
> You need to set the DEU region otherwise it will run against USA by default.

I change that simply in the read me and thats it?

Sorry

**Comment by LOX311** [comment]
> > If you're going to donate anywhere please donate here :)
> > https://donate.code.org/campaign/support-computer-science-education/c172233
> > You need to set the DEU region otherwise it will run against USA by default.
> 
> I change that simply in the read me and thats it?
> 
> Sorry

Nevermind, got it! thank you sir!

**Comment by ianmarmour** [comment]
No problem :)
