### ISSUE TITLE
Chrome is being controlled by automated test software

### ISSUE THREAD

**Issue by diprew** [ianmarmour/nvidia-clerk#57]
Is it possible for the program to open a regular Chrome window instead of a test environment? I would like to remain signed in on NVIDIA.com for checkout purposes.

**Comment by ianmarmour** [comment]
It's not possible to share a profile between the two browsers if that's what you're asking. Nothing should prevent you from logging into with this profile though.

**Comment by ianmarmour** [comment]
This is fixed in the latest release, it uses your default browser so you get to save your checkout info <3
