### ISSUE TITLE
Api Limit Request

### ISSUE THREAD

**Issue by coolfarmer** [ianmarmour/nvidia-clerk#58]
Just to let you know that having a delay of 2 seconds or less that 1 time on 3 we get an error that the api exceed the limit.
I'm currently using a delay of 3000 and it seems to be good!

Pretty use Nvidia put that limit yesterday with their new reCaptcha.

**Comment by ianmarmour** [comment]
I haven't notice any of these errors myself which version are you running and what region?

**Comment by coolfarmer** [comment]
I just updated to the last version like 10 minutes ago, and I'm currently using the region **CAN** .

It's more like 1 time on 20 now (with 2000ms)
Here is the error: https://i.imgur.com/3o8zUlh.png

**Comment by Altris001** [comment]
Same error, had to manually refresh to make it work again for few minutes

**Comment by coolfarmer** [comment]
More info here: https://www.reddit.com/r/nvidia/comments/iyaa48/captcha_will_not_help_mitigate_against_bots_as/

**Comment by ianmarmour** [comment]
I mean you'll see these no matter what, you're getting rate limited globally with all other NVIDIA users. We don't use bakeoff/retry logic because frankly nobody else is going to which is going to leave our users at a disadvantage if we implement it.
