### ISSUE TITLE
Target Machine Actively Refuses Connection

### ISSUE THREAD

**Issue by jacobfromNM** [ianmarmour/nvidia-clerk#6]
"http://localhost:9222/json/version": dial tcp [::1]:9222: connectex: No connection could be made because the target machine actively refused it." is the message received when attempting to run using latest Windows 10 update and latest Chrome update from the Downloads folder on the primary OS drive.

**Comment by ianmarmour** [comment]
Where is Chrome currently installed on your system?

**Comment by jacobfromNM** [comment]
C:\Program Files\Google\Chrome\Application\chrome.exe

**Comment by ianmarmour** [comment]
Can you try to run the command prompt as administrator? You may have some security policy blocking connections from localhost.

**Comment by jacobfromNM** [comment]
Unfortunately the issue persisted with the same message.

**Comment by Nanogamer7** [comment]
I'm getting a similar issue on MacOS
`Get "http://localhost:9222/json/version": dial tcp [::1]:9222: connect: connection refused`

Starting with sudo fixes this issue, however the enviromental variables aren't set when doing so
`NVIDIA_CLERK_SKU Environment Variable is unset, exiting.`

**Comment by ianmarmour** [comment]
If you're running as sudo you actually have different environment variables to sudo with your environment do,
```
sudo -E nvidia-clerk-darwin 
```
:)

**Comment by ianmarmour** [comment]
@jacobfromNM Is clerk opening up a chrome browser at all for you?

**Comment by jacobfromNM** [comment]
Not at all - and Chrome has been set as the default browser. I’ll keep trying...

Jacob Davis | jacobfromnm@gmail.com

**Comment by ianmarmour** [comment]
@jacobfromNM Are you using Powershell or cmd.exe (I've heard folks having issues in Powershell)

**Comment by Nanogamer7** [comment]
> If you're running as sudo you actually have different environment variables to sudo with your environment do,
> 
> ```
> sudo -E nvidia-clerk-darwin 
> ```
> 
> :)

That's on me, wasn't aware of it. However `sudo` only added terminated the script early because of the missing enviromental variables and didn't actually resolve the issue :(

> Not at all - and Chrome has been set as the default browser. I’ll keep trying...

On my end chrome actually opens, so I'm not 100% sure anymore if we are dealing with 2 different or the same issue. The error message does still look similar though.

**Comment by ianmarmour** [comment]
@Nanogamer7 Can you post me the exact commands and error you're getting (yours is mostly due to environmental variables on unix changing between administrator and non administrator permissions)

**Comment by Nanogamer7** [comment]
Sure:

With `sudo`:
```
 ~/Documents/NVidia-Clerk > export NVIDIA_CLERK_SKU=5438481700
 ~/Documents/NVidia-Clerk > export NVIDIA_CLERK_LOCALE=de-at
 ~/Documents/NVidia-Clerk > export NVIDIA_CLERK_CURRENCY=EUR
 ~/Documents/NVidia-Clerk > sudo -E ./nvidia-clerk-darwin
2020/09/21 08:41:54 Get "http://localhost:9222/json/version": dial tcp [::1]:9222: connect: connection refused
```
Without `sudo`:
```
 ~/Documents/NVidia-Clerk > export NVIDIA_CLERK_SKU=5438481700
 ~/Documents/NVidia-Clerk > export NVIDIA_CLERK_LOCALE=de-at
 ~/Documents/NVidia-Clerk > export NVIDIA_CLERK_CURRENCY=EUR
 ~/Documents/NVidia-Clerk > ./nvidia-clerk-darwin
2020/09/21 08:43:58 Get "http://localhost:9222/json/version": dial tcp [::1]:9222: connect: connection refused
```

However I made the interesting discovery, if I don't close Chrome after the error message, but instead execute the same command again I get a different error:
```
 ~/Documents/NVidia-Clerk > sudo -E ./nvidia-clerk-darwin
invalid character 'E' looking for beginning of value
Error getting SKU Information retrying...
invalid character 'E' looking for beginning of value
Error getting SKU Information retrying...
invalid character 'E' looking for beginning of value
Error getting SKU Information retrying...
invalid character 'E' looking for beginning of value
Error getting SKU Information retrying...
...
```

**Comment by ianmarmour** [comment]
Ah you're using an invalid SKU/Locale/Currency combination, things to try,

Switching the locale to de_DE and then updating the SKU to the one in the readme.

**Comment by Nanogamer7** [comment]
Switching to this combination does resolve the `invalid character` error, however, now I'm getting a _Privacy Error_ `NET::ERR_CERT_INVALID`, which didn't appear before.

**Comment by jacobfromNM** [comment]
@ianmarmour Resolved the issue by adding a rule in firewall settings to allow outgoing traffic.
