### ISSUE TITLE
when using -model=3090

### ISSUE THREAD

**Issue by Toiletduck34** [ianmarmour/nvidia-clerk#60]
Not sure if the SKU is out for the 3090 model yet. I am assuming since the new update it has been added but we are no longer using:
      "set NVIDIA_CLERK_SKU=5438481700"
When adding -model=3090 the chrome browser keeps updating which looks like it is continuously scanning the site for the SKU and the CMD is not updating,

is this normal until they launch when there is "stock"?

**Comment by vic18t** [comment]
If you test it with -model=3080, it works. So yes it appears to be scanning the entire nVidia catalog for the corresponding SKU until it shows up.

**Comment by penguinologist** [comment]
This is normal because digitalriver won't have the SKUs until about 30 minutes prior to launch

**Comment by Toiletduck34** [comment]
perfect, thank you. i didnt want to be rushing at 6am tomorrow to figure out something is wrong.

**Comment by mitchega** [comment]
When using cmd.exe to SKU the 3090 all I get is "nvidia-clerk-windows.exe is not recognized as an internal or external commnad, operable program or batch file."  Doesn't matter if I use "3080", I still get the same return prompt.  Guess I'm doing something incorrect?  Anyway you can create a seperate auto execute for the 3090 SKU?

**Comment by vic18t** [comment]
You’re in the wrong folder

**Comment by mitchega** [comment]
Folder? The .exe auto runs after I open it as an admin?

**Comment by vic18t** [comment]
Sorry man, teaching you how to use a computer is further than I’d like to help. There’s nothing wrong with the program.
