### ISSUE TITLE
Is there a way to start the bot via Batch?

### ISSUE THREAD

**Issue by SixtyGig** [ianmarmour/nvidia-clerk#63]
I'm trying to figure out if there's a way to automate the integration setup, because it's rather annoying to set this up every time I start the bot. 

This seems like a rather simple task, but I am having difficulty running more than one "set" command before my program stops. Open to input.

![image](https://user-images.githubusercontent.com/38166922/94054276-13161e00-fda1-11ea-8697-0fb889a8416c.png)

**Comment by penguinologist** [comment]
I think you've overthinking this. Here's my batch program

`set TWILIO_ACCOUNT_SID=XXXXXXXXXXXXXXXXXXXXXXXXX
set TWILIO_TOKEN=XXXXXXXXXXXXXXXXXXXXXXX
set TWILIO_SOURCE_NUMBER=+1XXXXXXXXXX
set TWILIO_DESTINATION_NUMBER=+1XXXXXXXXXX

nvidia-clerk-windows.exe -region=USA -delay=750`

The issue you're facing is that every time you run `start cmd`, it opens up a new command window and that's just gonna blow things up. just add all your values to one file, then run that file with the `start cmd` command

**Comment by SixtyGig** [comment]
Ah. Yes, it seems I way over complicated it. Thanks for the assistance! 😄
