### ISSUE TITLE
product id updated ??

### ISSUE THREAD

**Issue by ibot4fun** [ianmarmour/nvidia-clerk#64]
was the product id just changed?

**Comment by chronicrebellion** [comment]
definitely saw 502s at 4:06:31PM CST which then changed to 504 at 4:06:55PM CST

**Comment by ibot4fun** [comment]
where did you see 502's and now 504's? Trying to find out what the new product ID is. the old one was 5438481700.

**Comment by chronicrebellion** [comment]
https://in-and-ru-store-api.uk-e1.cloudhub.io/DR/products/en_us/USD/5438481700

**Comment by ZachTom2** [comment]
The API key changed
