### ISSUE TITLE
"We are sorry, an unexpected error occurred processing your request. Please try again."

### ISSUE THREAD

**Issue by rosherm** [ianmarmour/nvidia-clerk#65]
I can't get the bot to start up again. The webpage opens up and displays this message "We are sorry, an unexpected error occurred processing your request. Please try again.".

**Comment by 8uN** [comment]
same here

**Comment by captainbraz** [comment]
Same

![image](https://user-images.githubusercontent.com/71794097/94071137-4c05c100-fda8-11ea-89cb-826c99f174ba.png)

Chrome Version 85.0.4183.102 64 bit

**Comment by Sadge-spec** [comment]
Same

**Comment by ibot4fun** [comment]
i think they changed the product ID but i'm no expert. Will have to wait for dev

**Comment by Sadge-spec** [comment]
The product id is was changed from 502 to 504.

**Comment by 8uN** [comment]
aight thanks

**Comment by ibot4fun** [comment]
Product ID for the 3080 was = 5438481700

502 504?? confused

**Comment by ibot4fun** [comment]
how did you find product id change?

**Comment by ianmarmour** [comment]
Go back manual mode nvidia just pushed major changes, I'll try to update before launch be careful though.

**Comment by Sadge-spec** [comment]
Manual mode?

**Comment by ibot4fun** [comment]
I think he means. F5 to stay alive :)

**Comment by 8uN** [comment]
> Go back manual mode nvidia just pushed major changes, I'll try to update before launch be careful though.

What is "manual mode"

**Comment by 8uN** [comment]
> I think he means. F5 to stay alive :)

Ahh I see

**Comment by ZachTom2** [comment]
The API key changed

**Comment by tannguyen1024** [comment]
lol and they just dropped the cards.  Perfect timing.  haha

**Comment by 8uN** [comment]
my Recaptcha did not work didn't get a card im pissed

**Comment by ianmarmour** [comment]
@tannguyen1024 It was a good move on their part, they locked down all the API's made sure it there wasn't a checkout link on the existing checkout page lots of shit. I'll get at least the notifications back up and working later this evening but yeah RIP. (upside everyone else who was using bots had the same thing happen)

**Comment by J4YJ4YD** [comment]
> my Recaptcha did not work didn't get a card im pissed

Mine took too long and by the time I go to the order submission it was sold out.

**Comment by rixis19** [comment]
The 3080 went up to purchase? Dang

**Comment by J4YJ4YD** [comment]
> The 3080 went up to purchase? Dang

Yeah, at around 5:30PM CST. Gone  seconds later.

**Comment by rixis19** [comment]
> > The 3080 went up to purchase? Dang
> 
> Yeah, at around 5:30PM CST. Gone seconds later.

Thank you for the clarification, that's upsetting

**Comment by J4YJ4YD** [comment]
> Thank you for the clarification, that's upsetting

Yeah, managed to get it in the cart and fill out the info only to see the sold out message when I clicked submit!! Sigh...

**Comment by rixis19** [comment]
Did any of you get a notification email? I didn't again

**Comment by Art4Tech** [comment]
Wanted to say this was very cool to use and poke around in the source. Was just wondering if the api keys were originally revealed via inspection or some other means. Thanks my man. 
-also no, no notifications still

**Comment by J4YJ4YD** [comment]
No notification for me either.

**Comment by Art4Tech** [comment]
Getting locked out of the page when using a simple spamming F5 script and then realizing what an idiot I am... haha, should have known

**Comment by Art4Tech** [comment]
![NVidia Access Denied](https://user-images.githubusercontent.com/4230588/94082719-6c3c7c80-fdb6-11ea-9f8f-e7f245d0a2af.png)

**Comment by rixis19** [comment]
nice job nvidia

**Comment by J4YJ4YD** [comment]
Well, at the very least, I hope those that got it this time are actual consumers. I can handle missing out to other gamers. Just the resellers that piss me off!!

**Comment by BlueMoose68B** [comment]
Whats stopping them from just doing this everytime a card goes on sale is this the solution to beating bots?

**Comment by tannguyen1024** [comment]
Nothing.  But it's worth a shot.

**Comment by Art4Tech** [comment]
Good coders will find a way around the blockades ecommerce developers put up. That said, Nvidia has the money to actually change the game and make it really hard for the devs to code bots that they can make profit selling. I for one hope that they succeed.

**Comment by slurpee98** [comment]
Another upside is I really enjoyed learning the source and getting Twilio up and running. I’m usually just a circuit guy. So I like broadening my skills. Thanks!

**Comment by longgaminghours** [comment]
So I'm assuming this is no longer working now?

**Comment by ianmarmour** [comment]
New version getting launched in a min that will support notifying and opening browser to the product page, we don't have the feature for checkout again yet though.

**Comment by longgaminghours** [comment]
I will take what I can get I am pissed they restocked today and I missed it.

**Comment by vic18t** [comment]
> New version getting launched in a min that will support notifying and opening browser to the product page, we don't have the feature for checkout again yet though.

Thanks Ian. I'm curious if it possible to get the API token again? Or was the old one simply leaked?

**Comment by HiramIII** [comment]
When did the restock happen??

**Comment by longgaminghours** [comment]
I think around 6pm EST

**Comment by HiramIII** [comment]
Damn missed it again, maybe next time then.

**Comment by longgaminghours** [comment]
> Damn missed it again, maybe next time then.

These things don't even last long enough to checkout lol

**Comment by HiramIII** [comment]
> 
> 
> > Damn missed it again, maybe next time then.
> 
> These things don't even last long enough to checkout lol

You're right lol I'm still going to hold out for the FE though.

**Comment by ianmarmour** [comment]
> > New version getting launched in a min that will support notifying and opening browser to the product page, we don't have the feature for checkout again yet though.
> 
> Thanks Ian. I'm curious if it possible to get the API token again? Or was the old one simply leaked?

API token isn't going to do us much good, NVIDIA did a pretty great job at this actually.

So their digitalriver routes are being proxied through an NVIDIA API now (all Digital River API is restricted), then I'm assuming the requests are being proxied through their API where the key is being added (which we can't get)

That plus triple captcha means that basically if you didn't card another human did, botters and scalpers wouldn't have had time to react to these changes (I know I didn't 30 mins was all we had)

**Comment by ianmarmour** [comment]
Please see the updated README.md and latest release section for a "functional" version.

**Comment by balibou** [comment]
still having this issue with the last version :/

**Comment by ianmarmour** [comment]
This error only occurs when NVIDIA's site goes down I can add in functionality to retry multiple times to make sure we get a good URL but I'm not sure the best behavior yet regarding NVIDIA outages.

**Comment by ianmarmour** [comment]
This is gone now in the latest release :) <3
