### ISSUE TITLE
Error when running for 3090 with v2.4

### ISSUE THREAD

**Issue by OMGrant** [ianmarmour/nvidia-clerk#67]
C:\Users\me\Downloads>nvidia-clerk-windows.exe -region=USA -model=3090
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xfb26b9]

goroutine 1 [running]:
main.main()
        /home/runner/work/nvidia-clerk/nvidia-clerk/main.go:94 +0x599

C:\Users\me\Downloads>

**Comment by OMGrant** [comment]
Just saw update, bummer :(

**Comment by ianmarmour** [comment]
Yep, looking into it still but for right now we're dead for unknown SKUs

**Comment by ianmarmour** [comment]
See updated releases for support for 3090 in a few regions (USA/GBR) going to close this out now.
