### ISSUE TITLE
Country Locale

### ISSUE THREAD

**Issue by coolfarmer** [ianmarmour/nvidia-clerk#7]
Hello! 

First I need to say thanks you for your awesome job, that little monitor bot is really nice and it seems to work perfectly, even tested with -sms -test and a notification is correctly received :) .

But I have a question about the locale, I'm in Canada so I'm questioning myself if your bot will really work for me.
The bot currently echo "SKU Name: NVIDIA GEFORCE RTX 3080 - **US**"

Do you think it's possible to have "- CA"? Or maybe it's just the same locale for North America.
What's your thought on this?

Thanks again!

**Comment by coolfarmer** [comment]
Omg, I think you just push an update like 13 min ago when I was writing my message xD

**Comment by coolfarmer** [comment]
I just test your new variables but I don't think it work like I thought.

Here is my config:
set NVIDIA_CLERK_SKU=5438481700
set NVIDIA_CLERK_LOCALE=fr_ca
set NVIDIA_CLERK_CURRENCY=CAD
set (all sms things) ....

And here is the result (browser + cmd):
https://i.imgur.com/CCvltce.png

**Comment by ianmarmour** [comment]
So the issue here is that in CA they're going to use a different SKU number, you'll need to find the CA SKU for the 3080 to go alongside the rest of the configuration you have set. (I don't currently know or have all the SKU's for the different regions)

**Comment by coolfarmer** [comment]
Hum I see, do you know where I can find this number? Where have you found it for the US?

**Comment by coolfarmer** [comment]
I just found it in the API response but unfortunately it doesn't work:
https://i.imgur.com/dGWBRcW.png

**Comment by ianmarmour** [comment]
I'm wondering if that's actually the DigitalRiver SKU, it may be an internal one for Nvidia, trying to see.

**Comment by ianmarmour** [comment]
That looks like the model number not the SKU used by DigitalRiver, we need to find the DigitalRiver SKU for CA

**Comment by robertpan226** [comment]
That one is definitely not the DigitalRiver SKU, if you do the same for the US site you get "NVGFT080" not 5438481700.

**Comment by coolfarmer** [comment]
Yeah you are right, I'm currently looking at every API responses on every call made by their website (with my local set on en-us) but I don't know where he have found the SKU for his country (5438481700).

Maybe I don't look at the right place and there is an hidden inventory API.

**Comment by robertpan226** [comment]
I'm currently playing around with DigitalRiver's API

https://www.digitalriver.com/docs/commerce-api-reference/#tag/Products/paths/~1v1~1shoppers~1me~1products/get

**Comment by coolfarmer** [comment]
@ianmarmour , if you want to update your Readme, I just found the digitalRiver SKU for France (Europe)

Example for the frenchies who want to use it:
```
set NVIDIA_CLERK_SKU=5438795200
set NVIDIA_CLERK_LOCALE=fr_fr
set NVIDIA_CLERK_CURRENCY=EUR
```

But I can't find the one from Canada yet :/

**Comment by ianmarmour** [comment]
^^^ Same, already updated the readme.

**Comment by ianmarmour** [comment]
Also dang these inventory amounts in other countries have me feeling bad :/

**Comment by coolfarmer** [comment]
I'm start thinking that the SKU for USA and Canada is just the same.

**Comment by robertpan226** [comment]
![image](https://user-images.githubusercontent.com/10150017/93740770-26ff2b80-fbb9-11ea-9fee-85bc96a25ad2.png)
Hmm

**Comment by ianmarmour** [comment]
@robertpan226 What endpoint did you use to pull that?

**Comment by robertpan226** [comment]
![image](https://user-images.githubusercontent.com/10150017/93740885-5c0b7e00-fbb9-11ea-8fb4-ad84ed3f037c.png)
This is directly from Postman

**Comment by coolfarmer** [comment]
Damn I think you just confirmed it, and i'm not impressed, USA and Canada are both in North America, I think it's just "normal" to have the same SKU.

**Comment by ianmarmour** [comment]
It could be that the entire NA region uses the same SKUs, that being said you did set the CAD parameter in your get so who knows there. It's confusing that that would be the case considering FR and DE have different SKUs.... both are in the EU so ????

**Comment by robertpan226** [comment]
It's weird cause if you set locale=en-ca the SKU won't work, but if you set currency=CAD it does.

**Comment by ianmarmour** [comment]
Looks like we can get the SKUs here :) 

https://api.digitalriver.com/v1/shoppers/me/products?apiKey=9485fa7b159e42edb08a83bde0d83dia&locale=de_de&format=json&expand=product&fields=product.id,product.displayName,product.pricing&pageNUmber=5

**Comment by ianmarmour** [comment]
Going to be honest though I don't see anything for en_ca as a locale.... I think it might just be the en_us link :/

https://api.digitalriver.com/v1/shoppers/me/products?apiKey=9485fa7b159e42edb08a83bde0d83dia&locale=en_ca&format=json&expand=product&fields=product.id,product.displayName,product.pricing&pageNumber=1

**Comment by sgtzio** [comment]
Does anyone know how to find the SKU on the Norwegian locale?

**Comment by ianmarmour** [comment]
I just tried all the Norwegian locales and it doesn't look like it contains any products for any of them... does NVIDIA actually have a Norway specific store?

**Comment by Z4ckeh** [comment]
Post got deleted from Reddit. I will try here.

Someone posted DK SKU as: 5438793400

I tried with locale "da" first, but got this:

Set NVIDIA_CLERK_SKU=5438793400
Set NVIDIA_CLERK_LOCALE=DA
Set NVIDIA_CLERK_CURRENCY=DKK
Then I drag exe and run it. Chrome opens up and looks fine. But the cmd keeps saying:

"invalid character 'E' looking for beginning of value
Error getting SKU Information retrying..."

I tried changing to locale da_dk and got this:

set NVIDIA_CLERK_SKU=5438793400
set NVIDIA_CLERK_LOCALE=da_dk
set NVIDIA_CLERK_CURRENCY=dkk
nvidia-clerk-windows.exe"

panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.main()
        /home/runner/work/nvidia-clerk/nvidia-clerk/main.go:59 +0x785

Nvidia has a Danish specific store.

**Comment by sgtzio** [comment]
So what does it mean that Norway and Denmark have specific stores? Is this program incompatible?

**Comment by Z4ckeh** [comment]
I think we're just missing the right SKU. But I have no idea how to find it. I'm not tech-savvy, lol.

**Comment by mutantsofthemonster** [comment]
Norwegian SKU: 5438797200

Could not find any on the danish store...

**Comment by Z4ckeh** [comment]
sadface. Thanks for trying.

**Comment by sgtzio** [comment]
> 
> 
> Norwegian SKU: 5438797200
> 
> Could not find any on the danish store...

How did you find the Norwegian SKU?

**Comment by ianmarmour** [comment]
> > Norwegian SKU: 5438797200
> > Could not find any on the danish store...
> 
> How did you find the Norwegian SKU?

Agreed I wasn't able to find the norwegian locale/currency combo to pull this, can you please post those so we can update the readme with documentation for norway :)

**Comment by ianmarmour** [comment]
If someone has a working config for Locale/Currency/SKU for Norway let me know, I'll update the new region config section with it so that new users don't have to manually grab all this information and can just use the SKU.

**Comment by ianmarmour** [comment]
@coolfarmer Just want to clarify with you does using the USA store front with CAD as the currency solve this problem? As far as I can tell the CA store does not contain any SKU's for the 3080.

**Comment by Mitchell-T** [comment]
Is there a confirmed way to get the SKU's at this point? I've been trying to find the 3080 SKU number for the netherlands with no success

**Comment by ianmarmour** [comment]
CA support is now working using CAD and NA (please see latest release for supported region configurations)
