### ISSUE TITLE
Thanks man your a life saver you just got me a 3080.

### ISSUE THREAD

**Issue by 8uN** [ianmarmour/nvidia-clerk#70]
Just want to say thanks.

**Comment by ianmarmour** [comment]
I'm so happy to hear that, I actually just got one as well as another friend too glad to see this is working for people.

**Comment by 8uN** [comment]
<3

**Comment by vic18t** [comment]
You guys got it manually?

**Comment by ianmarmour** [comment]
Nope we got it using the new version of the bot that just opens the page :)

**Comment by borocode** [comment]
I got up from my computer to get an ice cream bar  and what do I see when I get back? yep, the only reason I got one tonight is because of this program. I shared the news manually in our Discord but it was too late for everyone else. Even paid for one day shipping...appreciate the hard work

**Comment by hymer08** [comment]
With the new version, it doesnt open a chrome page. Just the cmd out of stock tracker. Is this normal>

**Comment by coolfarmer** [comment]
OMG i'm fucking pissed, 5 SECONDS after the sms came in I was FREEZE on the button "Checking out...." 

This is crazy :'(

**Comment by vic18t** [comment]
> Nope we got it using the new version of the bot that just opens the page :)

*sigh* does the sms alerts still work in this version?

**Comment by coolfarmer** [comment]
> 
> 
> > Nope we got it using the new version of the bot that just opens the page :)
> 
> _sigh_ does the sms alerts still work in this version?

Yes it worked, the SMS came in extremely fast, I clicked on "Add to cart" then "Checkout" and was stuck on "Checking out..." state for ever

**Comment by hymer08** [comment]
Can someone help me set up the sms? xD Im a total noob and barely got the normal thing working

**Comment by vic18t** [comment]
Gratz to all! Any hope for getting this to work with the 3090?

**Comment by ianmarmour** [comment]
> With the new version, it doesnt open a chrome page. Just the cmd out of stock tracker. Is this normal>

Yes, it will open a browser when a card comes in stock.

**Comment by ianmarmour** [comment]
> Gratz to all! Any hope for getting this to work with the 3090?

I've been trying some... interesting methods to get the sku's but haven't been successful so far.

**Comment by Mathametic** [comment]
I want to add to this to say that I also got my order thanks to your bot, so I also want to say that you rock! I literally laid down in bed, grabbed my phone to turn on the sound so I could hear if I got a notification (Just expecting it to be false hope but y'know, gotta pray) and right as I grabbed my phone, the Discord webhook told me to get out of bed and get the card. Never before has my fat ass sprinted so fast down and up two flights of stairs to grab my credit card.

**Comment by ibot4fun** [comment]
same. got my order processed tonight with this one. Ian you're the man! I need 1 more for the wife and our dual monsters in tiny box projects are complete.

Was sitting on my desk playing final fantasy 14 when my 2nd monitor opened the page. was very smooth. 2nd attempt not so smooth. website was already flooded

**Comment by vic18t** [comment]
> > Gratz to all! Any hope for getting this to work with the 3090?
> 
> I've been trying some... interesting methods to get the sku's but haven't been successful so far.

Lol. Have you tried brute force? nVidia SKU’s seem pretty close to each other by a few thousand or so...just keep looping until it hits something.

**Comment by Raphael-Lemercier** [comment]
Since yesterday the program doesn't work for me for every version.
"flag provided but not defined: -region:FRA"
"flag provided but not defined: -region:USA"
Which region do you set for ?

**Comment by joohanp** [comment]
You need to use -region=FRA instead of -region:FRA

**Comment by Raphael-Lemercier** [comment]
Omg thanks dude

**Comment by ianmarmour** [comment]
> > > Gratz to all! Any hope for getting this to work with the 3090?
> > 
> > 
> > I've been trying some... interesting methods to get the sku's but haven't been successful so far.
> 
> Lol. Have you tried brute force? nVidia SKU’s seem pretty close to each other by a few thousand or so...just keep looping until it hits something.

Indeed I have, no good results yet. Won’t have support for 3090 on launch day sadly.

**Comment by slurpee98** [comment]
Bah.  Stupid mistake on my part.  SMS is working fine.  But I forgot to turn off the power saving sleep timers in Windows before going to bed.  I'm thrilled to see real folks getting their cards though. Congrats! I'll keep trying.

**Comment by longgaminghours** [comment]
Does anyone know when they will restock again?

**Comment by 8uN** [comment]
probably next week, don't quote me on that but I would have the bot running overnight.
