### ISSUE TITLE
SMS Help

### ISSUE THREAD

**Issue by hymer08** [ianmarmour/nvidia-clerk#72]
Im trying to figure out the sms.

set TWILIO_ACCOUNT_SID=YOUR_TWILIO_ACCOUNT_SID_HERE
set TWILIO_TOKEN=YOUR_TWILIO_TOKEN_HERE
set TWILIO_SOURCE_NUMBER=YOUR_TWILIO_SERVICE_NUMBER_HERE
set TWILIO_DESTINATION_NUMBER=YOUR_DESITNATION_NUMBER_FOR_NOTIFICATIONS_HERE

This for example, where would i input this? I already made a twilio acocount. Please help :0

**Comment by vic18t** [comment]
Go to your twilio dashboard. it will all be there (token and sid)

**Comment by hymer08** [comment]
Yeah i found it on the twilio, but im confused as to how i integrate it with the cmd stuff yknow?

**Comment by vic18t** [comment]
replace the YOUR_TWILIO_ACCOUNT_SID_HERE with your SID....etc

**Comment by hymer08** [comment]
When i have everything filled in do i post it into the cmd along with the exe file and region stuff?

**Comment by hymer08** [comment]
Also thanks for trying to help, i really dont know much about this

**Comment by vic18t** [comment]
each line is a command that you press return on. But if you copy and paste everything into the command line (with line breaks) it should work

**Comment by vic18t** [comment]
> Also thanks for trying to help, i really dont know much about this

No worries. Then test it out with nvidia-clerk-windows -sms -test

**Comment by hymer08** [comment]
So normally i do this:

nvidia-clerk-windows.exe -region=USA -model=3080

Do i do this now then?

nvidia-clerk-windows.exe -region=USA -model=3080
set TWILIO_ACCOUNT_SID=YOUR_TWILIO_ACCOUNT_SID_HERE
set TWILIO_TOKEN=YOUR_TWILIO_TOKEN_HERE
set TWILIO_SOURCE_NUMBER=YOUR_TWILIO_SERVICE_NUMBER_HERE
set TWILIO_DESTINATION_NUMBER=YOUR_DESITNATION_NUMBER_FOR_NOTIFICATIONS_HERE

Obviously with my info filled in?

**Comment by vic18t** [comment]
No set the variables first

**Comment by hymer08** [comment]
set TWILIO_ACCOUNT_SID=YOUR_TWILIO_ACCOUNT_SID_HERE
set TWILIO_TOKEN=YOUR_TWILIO_TOKEN_HERE
set TWILIO_SOURCE_NUMBER=YOUR_TWILIO_SERVICE_NUMBER_HERE
set TWILIO_DESTINATION_NUMBER=YOUR_DESITNATION_NUMBER_FOR_NOTIFICATIONS_HERE
nvidia-clerk-windows.exe -sms -region=USA -model=3080

Like this?

**Comment by vic18t** [comment]
yes but i strongly suggest testing first with nvidia-clerk-windows.exe -sms -test

**Comment by hymer08** [comment]
Ill try it now

**Comment by hymer08** [comment]
Holy crap it worked lol, i set up the usage one. Thanks so much!

**Comment by vic18t** [comment]
Glad to help!

**Comment by FROOGLEPOWER** [comment]
> Glad to help!

Not OP but also not very smart,
What's the difference between TWILIO_SOURCE_NUMBER, YOUR_TWILIO_SERVICE_NUMBER_HERE, TWILIO_DESTINATION_NUMBER and YOUR_DESITNATION_NUMBER_FOR_NOTIFICATIONS_HERE?
