### ISSUE TITLE
Bot not working

### ISSUE THREAD

**Issue by HiramIII** [ianmarmour/nvidia-clerk#73]
I keep getting this error

Exception 0xc0000005 0x0 0x7ffb2cbf2fff 0x1f07b800000
PC=0x1f07b800000

syscall.Syscall6(0x7ffb2b3e5b20, 0x4, 0xc00002e480, 0x0, 0xc000069f18, 0xc000069e90, 0x0, 0x0, 0x0, 0x0, ...)
        /opt/hostedtoolcache/go/1.15.2/x64/src/runtime/syscall_windows.go:201 +0xf2
syscall.GetAddrInfoW(0xc00002e480, 0x0, 0xc000069f18, 0xc000069e90, 0x14, 0x0)
        /opt/hostedtoolcache/go/1.15.2/x64/src/syscall/zsyscall_windows.go:1718 +0xe5
net.(*Resolver).lookupIP.func1(0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/lookup_windows.go:109 +0x259
net.(*Resolver).lookupIP.func2(0xc000004940, 0xc000189c20)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/lookup_windows.go:146 +0x32
created by net.(*Resolver).lookupIP
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/lookup_windows.go:145 +0x41b

goroutine 1 [select]:
net/http.(*Transport).getConn(0x140bc80, 0xc000070500, 0x0, 0xc0000325a0, 0x5, 0xc00002cbe0, 0x17, 0x0, 0x0, 0x0, ...)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/http/transport.go:1347 +0x5ac
net/http.(*Transport).roundTrip(0x140bc80, 0xc00018c200, 0x10b9220, 0xc00017a701, 0xc00018c200)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/http/transport.go:569 +0x79c
net/http.(*Transport).RoundTrip(0x140bc80, 0xc00018c200, 0x140bc80, 0xbfd329137021a180, 0x3073b9521)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/http/roundtrip.go:17 +0x3c
net/http.send(0xc00018c100, 0x115a520, 0x140bc80, 0xbfd329137021a180, 0x3073b9521, 0x1411f60, 0xc000006058, 0xbfd329137021a180, 0x1, 0x0)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/http/client.go:252 +0x473
net/http.(*Client).send(0xc00017a6f0, 0xc00018c100, 0xbfd329137021a180, 0x3073b9521, 0x1411f60, 0xc000006058, 0x0, 0x1, 0xc00018c100)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/http/client.go:176 +0x105
net/http.(*Client).do(0xc00017a6f0, 0xc00018c100, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/http/client.go:718 +0x45f
net/http.(*Client).Do(...)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/http/client.go:586
net/http.(*Client).Get(0xc00017a6f0, 0xc0000325a0, 0x4e, 0x3, 0x3, 0xc0000325a0)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/http/client.go:475 +0xc5
github.com/ianmarmour/nvidia-clerk/internal/rest.GetSkuInfo(0x10c5249, 0xa, 0x10c35bf, 0x5, 0x10c2f0d, 0x3, 0xc00017a6f0, 0x0, 0x0, 0x0)
        /home/runner/work/nvidia-clerk/nvidia-clerk/internal/rest/rest.go:103 +0x198
main.main()
        /home/runner/work/nvidia-clerk/nvidia-clerk/main.go:94 +0x5de

goroutine 6 [select]:
net.(*Resolver).lookupIPAddr(0x1411540, 0x11603a0, 0xc000189800, 0x10c2f91, 0x3, 0xc00002cbe0, 0x13, 0x1bb, 0x0, 0x0, ...)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/lookup.go:299 +0x685
net.(*Resolver).internetAddrList(0x1411540, 0x11603a0, 0xc000189800, 0x10c2f91, 0x3, 0xc00002cbe0, 0x17, 0x0, 0x0, 0x0, ...)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/ipsock.go:280 +0x4d4
net.(*Resolver).resolveAddrList(0x1411540, 0x11603a0, 0xc000189800, 0x10c3204, 0x4, 0x10c2f91, 0x3, 0xc00002cbe0, 0x17, 0x0, ...)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/dial.go:221 +0x49d
net.(*Dialer).DialContext(0xc00003a1e0, 0x11603a0, 0xc000189800, 0x10c2f91, 0x3, 0xc00002cbe0, 0x17, 0x0, 0x0, 0x0, ...)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/dial.go:403 +0x23c
net/http.(*Transport).dial(0x140bc80, 0x11603a0, 0xc000189800, 0x10c2f91, 0x3, 0xc00002cbe0, 0x17, 0x0, 0x0, 0x0, ...)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/http/transport.go:1141 +0x1fd
net/http.(*Transport).dialConn(0x140bc80, 0x11603a0, 0xc000189800, 0x0, 0xc0000325a0, 0x5, 0xc00002cbe0, 0x17, 0x0, 0xc000134c60, ...)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/http/transport.go:1575 +0x1adb
net/http.(*Transport).dialConnFor(0x140bc80, 0xc0001402c0)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/http/transport.go:1421 +0xcd
created by net/http.(*Transport).queueForDial
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/http/transport.go:1390 +0x40f

goroutine 7 [select]:
net.(*Resolver).lookupIP(0x1411540, 0x1160320, 0xc000070580, 0x10c2f91, 0x3, 0xc00002cbe0, 0x13, 0x0, 0x0, 0x0, ...)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/lookup_windows.go:151 +0x1b9
net.glob..func1(0x1160320, 0xc000070580, 0xc0000670f0, 0x10c2f91, 0x3, 0xc00002cbe0, 0x13, 0xc000189800, 0x0, 0xc0000325a0, ...)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/hook.go:23 +0x79
net.(*Resolver).lookupIPAddr.func1(0x0, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/lookup.go:293 +0xc2
internal/singleflight.(*Group).doCall(0x1411550, 0xc000072230, 0xc00002cce0, 0x17, 0xc0000705c0)
        /opt/hostedtoolcache/go/1.15.2/x64/src/internal/singleflight/singleflight.go:95 +0x35
created by internal/singleflight.(*Group).DoChan
        /opt/hostedtoolcache/go/1.15.2/x64/src/internal/singleflight/singleflight.go:88 +0x2cc
rax     0x7ffb298b0852
rbx     0x7ffb298b0850
rcx     0x77
rdi     0xffffffffffbadd11
rsi     0x0
rbp     0x0
rsp     0x9289fe5d0
r8      0x97c
r9      0x97c
r10     0x97c
r11     0x97c
r12     0xc000007a
r13     0x0
r14     0x7ffb298b0852
r15     0x7ffb2c9f0000
rip     0x1f07b800000
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b

**Comment by vic18t** [comment]
What command did you run?

**Comment by HiramIII** [comment]
nvidia-clerk-windows.exe -region=USA -model=3080

**Comment by HiramIII** [comment]
> 
> 
> What command did you run?

nvidia-clerk-windows.exe -region=USA -model=3080

**Comment by HiramIII** [comment]
Is this the wrong code?

**Comment by HiramIII** [comment]
@vic18t Is this the right code

**Comment by vic18t** [comment]
That looks correct. I'm not sure what it could be. What version of the .exe are you running? And are you on Windows 10?

**Comment by HiramIII** [comment]
> 
> 
> That looks correct. I'm not sure what it could be. What version of the .exe are you running? And are you on Windows 10?

I'm using V2.4 and yes I'm on windows 10

**Comment by HiramIII** [comment]
Restarted and everything and the issue still exist

**Comment by HiramIII** [comment]
@ianmarmour any idea why I'm getting this?

**Comment by ianmarmour** [comment]
Nope there's 1 other user with that error I can only assume it's something environment specific,

I.E.

1. You're using a "semi" mobile ARM based platform like the service
2. You have a firewall blocking requests to localhost or ephemeral ports (ports in the range 49152 to 65535)
3. Some other system specific configuration that I'm not taking into account.

**Comment by HiramIII** [comment]
> 
> 
> Nope there's 1 other user with that error I can only assume it's something environment specific,
> 
> I.E.
> 
>     1. You're using a "semi" mobile ARM based platform like the service
> 
>     2. You have a firewall blocking requests to localhost or ephemeral ports (ports in the range 49152 to 65535)
> 
>     3. Some other system specific configuration that I'm not taking into account.

Hmm It was working just fine on the previous versions, I haven't changed anything since then. Interesting

**Comment by ianmarmour** [comment]
Random question do you have an IPv6 or IPv4 address? If this is a bug it's probably in GoLang itself (we migrated to using GoLangs built in HTTP provider vs using chrome probably why you're seeing the change) but considering it's a part of GoLangs standard library this would be a crazy oversight (You might be getting timeouts as well there's a 10 second max timeout duration but I doubt this very much.)

**Comment by HiramIII** [comment]
> 
> 
> Random question do you have an IPv6 or IPv4 address? If this is a bug it's probably in GoLang itself (we migrated to using GoLangs built in HTTP provider vs using chrome probably why you're seeing the change) but considering it's a part of GoLangs standard library this would be a crazy oversight (You might be getting timeouts as well there's a 10 second max timeout duration but I doubt this very much.)

I have an IPv4 address and if it's in the case of the timeout then it is definitely less than the max 10 seconds

**Comment by ianmarmour** [comment]
@HiramIII So I think this is related to,

https://github.com/golang/go/issues/30310

Can you try the attached version and let me know if it works


[nvidia-clerk-windows.zip](https://github.com/ianmarmour/nvidia-clerk/files/5278225/nvidia-clerk-windows.zip)

**Comment by HiramIII** [comment]
> 
> 
> @HiramIII So I think this is related to,
> 
> [golang/go#30310](https://github.com/golang/go/issues/30310)
> 
> Can you try the attached version and let me know if it works
> 
> [nvidia-clerk-windows.zip](https://github.com/ianmarmour/nvidia-clerk/files/5278225/nvidia-clerk-windows.zip)

Still no luck, here I included some screenshots 

https://imgur.com/a/SYDrtuI

**Comment by ianmarmour** [comment]
At this point I would say this is an anti-virus or security problem,

https://github.com/golang/go/issues/40878

Can you temporarily disable any AV you have running on your system or whitelist this program to not be filtered by it.

**Comment by HiramIII** [comment]
> 
> 
> At this point I would say this is an anti-virus or security problem,
> 
> [golang/go#40878](https://github.com/golang/go/issues/40878)
> 
> Can you temporarily disable any AV you have running on your system or whitelist this program to not be filtered by it.

So everything was disabled and I whitelisted, however new codes popped up: https://imgur.com/a/fwW5fcH

**Comment by ianmarmour** [comment]
@Hiramlll

Lets try this again :) (tried another change)
[nvidia-clerk-windows.zip](https://github.com/ianmarmour/nvidia-clerk/files/5278538/nvidia-clerk-windows.zip)

Fix attempted is disabling CGO compiling for interested readers,

https://github.com/golang/go/issues/18588

**Comment by HiramIII** [comment]
> @Hiramlll
> 
> 
> 
> Lets try this again :) (tried another change)
> 
> [nvidia-clerk-windows.zip](https://github.com/ianmarmour/nvidia-clerk/files/5278538/nvidia-clerk-windows.zip)
> 
> 
> 
> Fix attempted is disabling CGO compiling for interested readers,
> 
> 
> 
> https://github.com/golang/go/issues/18588



I will try once I get home, thank you for helping me I really appreciate it!

**Comment by ianmarmour** [comment]
Might as well just pull the latest release it has these changes in it and add's autocheckout support and remote mode.

**Comment by HiramIII** [comment]
> 
> 
> Might as well just pull the latest release it has these changes in it and add's autocheckout support and remote mode.

The new release fixed the issue! Thank you!
