### ISSUE TITLE
delay is not working

### ISSUE THREAD

**Issue by Moortu** [ianmarmour/nvidia-clerk#74]
I use the delay flag, but no matter what I enter it always refreshes every 3+- sec.

Doesn't seem to be used in the code? at least not in main

**Comment by coolfarmer** [comment]
From the Readme: _What this means for clerk, you won't get automatical checkout addition anymore just notifications of in stock inventory and the a browser open for you to add it to your cart. **We added some basic randomization of request times too just in case**._

I don't think -delay should be used with the last version.

**Comment by Moortu** [comment]
but instead of querying every 3 sec I rather query every 30 sec or even 60 sec

**Comment by MauriceW67** [comment]
Agreed. Despite the added randomization, the delay option should still work IMHO.

**Comment by infernix** [comment]
Should just parametrize it. Here's a quick hack.
```diff
diff --git a/main.go b/main.go
index 95f9391..1eef1c1 100644
--- a/main.go
+++ b/main.go
@@ -88,7 +88,8 @@ func main() {
 
        for {
                rand.Seed(time.Now().UnixNano())
-               n := rand.Intn(5)
+               n := rand.Intn(5) + 15
+               log.Println(fmt.Sprintf("sleep for duration %v", n))
                time.Sleep(time.Duration(n) * time.Second)
 
                info, err := rest.GetSkuInfo(*config.SKU, config.Locale, config.Currency, client)
```

So a base (15 here) plus a random (5). should be trivial.

**Comment by ianmarmour** [comment]
Fixed by https://github.com/ianmarmour/nvidia-clerk/releases/tag/v2.8

Closing
