### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by captainbraz** [ianmarmour/nvidia-clerk#75]
C:\Users\               \Desktop>nvidia-clerk-windows.exe -region=USA -model=3080
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.main()
        /home/runner/work/nvidia-clerk/nvidia-clerk/main.go:99 +0xed3

**Comment by captainbraz** [comment]
It did that a few times when I ran it. restarted 3 times and it would just throw that error each time. Waited about 2 minutes, restarted and is working now.

**Comment by b-lawler** [comment]
Just received the same error.  It ran for a little over an hour before erroring out.  Restarted fine a few min ago.

**Comment by coolfarmer** [comment]
Maybe it's part of their new "security system". They have drop another batch of cards and the script give me that error just before.

**Comment by drkztan** [comment]
I'm going to try to fix it gimme a few hours lol

**Comment by kiss81** [comment]
issue is still there when using -model=3090 (region doesn't seem to matter here)

**Comment by longgaminghours** [comment]
I am now getting this error

**Comment by ianmarmour** [comment]
Fixed in the latest release, closing this out.
