### ISSUE TITLE
SMS Twilio via Mac

### ISSUE THREAD

**Issue by duckpond85** [ianmarmour/nvidia-clerk#76]
noob here but trying to get sms notification working

have twilio account set up and have assigned the given SID,token, twilio number and my own number input on each line correctly,  but when i execute the commands in terminal it gives error below

Twilio: TWILIO_ACCOUNT_SID Environment variable not found

**Comment by ianmarmour** [comment]
You've messed up configurating those environmental variables try the README for how to do it on a Mac, outside of that this isn't an issue so I'm going to close it.
