### ISSUE TITLE
Direct Cart link FYI

### ISSUE THREAD

**Issue by vic18t** [ianmarmour/nvidia-clerk#77]
@ianmarmour are you using the ATC link in your latest implementation? They work again.

https://store.nvidia.com/store?Action=AddItemToRequisition&SiteID=nvidia&Locale=en_US&productID=5438481700&quantity=1

**Comment by ianmarmour** [comment]
I haven’t not can update tomorrow or someone can submit a pr for it.

**Comment by Sadge-spec** [comment]
Pause. The direct link stopped working.

**Comment by ianmarmour** [comment]
Yeah I also kinda figured this, last night I was trying to find SKU's poking through the source and it looks like (to my eyes at least) that there is a captcha before the checkout cart that's sent as a token alongside the add to cart request (which if it didn't already would break this link)

**Comment by Sadge-spec** [comment]
So is there an alternative for this?

**Comment by ianmarmour** [comment]
Clicking the add to cart button for now

**Comment by Sadge-spec** [comment]
I tried that last night but captcha wouldn't even pop up.

**Comment by ianmarmour** [comment]
@Sadge-spec Just a matter of speed, their captcha service ended up falling over with increased traffic
