### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by MrMightyNighty** [ianmarmour/nvidia-clerk#8]
System:
Windows 10 1909 18363.1082
Chrome: 85.0.4183.102

Variables:
SKU: 5438792300 (Germany)
Locale: de-de
Currency: EUR

I'm getting an "index out of range" error as soon as I start it. All variables are set.

Exception: 
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.main()
        /home/runner/work/nvidia-clerk/nvidia-clerk/main.go:33 +0x625

**Comment by ianmarmour** [comment]
Can you try the locale de_DE

**Comment by MrMightyNighty** [comment]
Still same issue.

**Comment by ianmarmour** [comment]
If you downloaded the latest release and only set the SKU to DE this should now be fixed, let me know if that's not the case going to close this out for now.

**Comment by MrMightyNighty** [comment]
Works perfectly. Maybe I didn't had the latest release in the first place. v0.2 shows as the first in the release list (at least for me)
I blindly downloaded it...
