### ISSUE TITLE
Bot not working, something might have changed after the 3090 launch

### ISSUE THREAD

**Issue by StanleyAlbayeros** [ianmarmour/nvidia-clerk#82]
So, my bot was running through the 3090 launch, but I'm only looking for a 3080. Last output before it stopped working:

```
2020/09/24 15:14:21 Product ID: 5438794800
2020/09/24 15:14:21 Product Name: NVIDIA GEFORCE RTX 3080 - ES
2020/09/24 15:14:21 Product Locale: es_es
2020/09/24 15:14:21 Product Status: PRODUCT_INVENTORY_OUT_OF_STOCK

Error attempting to access URL: https://api-prod.nvidia.com/direct-sales-shop/DR/products/es_es/EUR/5438794800
Error attempting to access URL: https://api-prod.nvidia.com/direct-sales-shop/DR/products/es_es/EUR/5438794800
Error attempting to access URL: https://api-prod.nvidia.com/direct-sales-shop/DR/products/es_es/EUR/5438794800
Error attempting to access URL: https://api-prod.nvidia.com/direct-sales-shop/DR/products/es_es/EUR/5438794800
invalid character '<' looking for beginning of value
Error attempting to access URL: https://api-prod.nvidia.com/direct-sales-shop/DR/products/es_es/EUR/5438794800
Error attempting to access URL: https://api-prod.nvidia.com/direct-sales-shop/DR/products/es_es/EUR/5438794800
invalid character '<' looking for beginning of value
```

After that I tested with 
`.\nvidia-clerk-windows.exe -region=ESP -test` 
which got me:
`Error attempting to access URL: https://api-prod.nvidia.com/direct-sales-shop/DR/products/es_es/EUR/`

**Comment by hymer08** [comment]
same

**Comment by HiramIII** [comment]
I'm getting this still, 

Exception 0xc0000005 0x0 0x7ff9e41d2fff 0x1f03b000000
PC=0x1f03b000000

syscall.Syscall6(0x7ff9e2c35b20, 0x4, 0xc00002c4b0, 0x0, 0xc000069f18, 0xc000069e90, 0x0, 0x0, 0x0, 0x0, ...)
        /opt/hostedtoolcache/go/1.15.2/x64/src/runtime/syscall_windows.go:201 +0xf2
syscall.GetAddrInfoW(0xc00002c4b0, 0x0, 0xc000069f18, 0xc000069e90, 0x14, 0x0)
        /opt/hostedtoolcache/go/1.15.2/x64/src/syscall/zsyscall_windows.go:1718 +0xe5
net.(*Resolver).lookupIP.func1(0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/lookup_windows.go:109 +0x259
net.(*Resolver).lookupIP.func2(0xc000004940, 0xc00018bc20)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/lookup_windows.go:146 +0x32
created by net.(*Resolver).lookupIP
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/lookup_windows.go:145 +0x41b

goroutine 1 [select]:
net/http.(*Transport).getConn(0xb3bc80, 0xc000070500, 0x0, 0xc0000325a0, 0x5, 0xc000030bc0, 0x17, 0x0, 0x0, 0x0, ...)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/http/transport.go:1347 +0x5ac
net/http.(*Transport).roundTrip(0xb3bc80, 0xc00018e200, 0x7e9220, 0xc00017c701, 0xc00018e200)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/http/transport.go:569 +0x79c
net/http.(*Transport).RoundTrip(0xb3bc80, 0xc00018e200, 0xb3bc80, 0xbfd345e700d90634, 0x28fff6acd)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/http/roundtrip.go:17 +0x3c
net/http.send(0xc00018e100, 0x88a520, 0xb3bc80, 0xbfd345e700d90634, 0x28fff6acd, 0xb41f60, 0xc000006058, 0xbfd345e700d90634, 0x1, 0x0)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/http/client.go:252 +0x473
net/http.(*Client).send(0xc00017c6f0, 0xc00018e100, 0xbfd345e700d90634, 0x28fff6acd, 0xb41f60, 0xc000006058, 0x0, 0x1, 0xc00018e100)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/http/client.go:176 +0x105
net/http.(*Client).do(0xc00017c6f0, 0xc00018e100, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/http/client.go:718 +0x45f
net/http.(*Client).Do(...)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/http/client.go:586
net/http.(*Client).Get(0xc00017c6f0, 0xc0000325a0, 0x4e, 0x3, 0x3, 0xc0000325a0)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/http/client.go:475 +0xc5
github.com/ianmarmour/nvidia-clerk/internal/rest.GetSkuInfo(0x7f5249, 0xa, 0x7f35bf, 0x5, 0x7f2f0d, 0x3, 0xc00017c6f0, 0x0, 0x0, 0x0)
        /home/runner/work/nvidia-clerk/nvidia-clerk/internal/rest/rest.go:103 +0x198
main.main()
        /home/runner/work/nvidia-clerk/nvidia-clerk/main.go:94 +0x5de

goroutine 6 [select]:
net.(*Resolver).lookupIPAddr(0xb41540, 0x8903a0, 0xc00018b800, 0x7f2f91, 0x3, 0xc000030bc0, 0x13, 0x1bb, 0x0, 0x0, ...)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/lookup.go:299 +0x685
net.(*Resolver).internetAddrList(0xb41540, 0x8903a0, 0xc00018b800, 0x7f2f91, 0x3, 0xc000030bc0, 0x17, 0x0, 0x0, 0x0, ...)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/ipsock.go:280 +0x4d4
net.(*Resolver).resolveAddrList(0xb41540, 0x8903a0, 0xc00018b800, 0x7f3204, 0x4, 0x7f2f91, 0x3, 0xc000030bc0, 0x17, 0x0, ...)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/dial.go:221 +0x49d
net.(*Dialer).DialContext(0xc00003a1e0, 0x8903a0, 0xc00018b800, 0x7f2f91, 0x3, 0xc000030bc0, 0x17, 0x0, 0x0, 0x0, ...)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/dial.go:403 +0x23c
net/http.(*Transport).dial(0xb3bc80, 0x8903a0, 0xc00018b800, 0x7f2f91, 0x3, 0xc000030bc0, 0x17, 0x0, 0x0, 0x0, ...)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/http/transport.go:1141 +0x1fd
net/http.(*Transport).dialConn(0xb3bc80, 0x8903a0, 0xc00018b800, 0x0, 0xc0000325a0, 0x5, 0xc000030bc0, 0x17, 0x0, 0xc000134d80, ...)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/http/transport.go:1575 +0x1adb
net/http.(*Transport).dialConnFor(0xb3bc80, 0xc0001402c0)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/http/transport.go:1421 +0xcd
created by net/http.(*Transport).queueForDial
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/http/transport.go:1390 +0x40f

goroutine 7 [select]:
net.(*Resolver).lookupIP(0xb41540, 0x890320, 0xc000070580, 0x7f2f91, 0x3, 0xc000030bc0, 0x13, 0x0, 0x0, 0x0, ...)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/lookup_windows.go:151 +0x1b9
net.glob..func1(0x890320, 0xc000070580, 0xc0000670f0, 0x7f2f91, 0x3, 0xc000030bc0, 0x13, 0xc00018b800, 0x0, 0xc0000325a0, ...)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/hook.go:23 +0x79
net.(*Resolver).lookupIPAddr.func1(0x0, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.15.2/x64/src/net/lookup.go:293 +0xc2
internal/singleflight.(*Group).doCall(0xb41550, 0xc000072230, 0xc000030cc0, 0x17, 0xc0000705c0)
        /opt/hostedtoolcache/go/1.15.2/x64/src/internal/singleflight/singleflight.go:95 +0x35
created by internal/singleflight.(*Group).DoChan
        /opt/hostedtoolcache/go/1.15.2/x64/src/internal/singleflight/singleflight.go:88 +0x2cc
rax     0x7ff9e0e90852
rbx     0x7ff9e0e90850
rcx     0x77
rdi     0xffffffffffbadd11
rsi     0x0
rbp     0x0
rsp     0x72f29fe9a0
r8      0x97c
r9      0x97c
r10     0x97c
r11     0x97c
r12     0xc000007a
r13     0x0
r14     0x7ff9e0e90852
r15     0x7ff9e3fd0000
rip     0x1f03b000000
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b

**Comment by HiramIII** [comment]
How are you guys running the bot, it was working before for me, now it doesn't.

**Comment by hymer08** [comment]
Bot is working again, are you running the new version released last night?

**Comment by rosherm** [comment]
I'm getting the error message about 10 times in a row then it works like it should. I think the website is just crashing right now.

**Comment by hymer08** [comment]
Yeah website is the issue, i noticed that when the OOS disappears the bot stops. But there is still no stock

**Comment by HiramIII** [comment]
Yeah version 2.4, It wasn't working before the 3090 launch either.

**Comment by vic18t** [comment]
I have 2.4 working fine.  OP, the errors that you are seeing are because the nVidia servers are being slammed.

> So, my bot was running through the 3090 launch, but I'm only looking for a 3080. Last output before it stopped working:
> 
> ```
> 2020/09/24 15:14:21 Product ID: 5438794800
> 2020/09/24 15:14:21 Product Name: NVIDIA GEFORCE RTX 3080 - ES
> 2020/09/24 15:14:21 Product Locale: es_es
> 2020/09/24 15:14:21 Product Status: PRODUCT_INVENTORY_OUT_OF_STOCK
> 
> Error attempting to access URL: https://api-prod.nvidia.com/direct-sales-shop/DR/products/es_es/EUR/5438794800
> Error attempting to access URL: https://api-prod.nvidia.com/direct-sales-shop/DR/products/es_es/EUR/5438794800
> Error attempting to access URL: https://api-prod.nvidia.com/direct-sales-shop/DR/products/es_es/EUR/5438794800
> Error attempting to access URL: https://api-prod.nvidia.com/direct-sales-shop/DR/products/es_es/EUR/5438794800
> invalid character '<' looking for beginning of value
> Error attempting to access URL: https://api-prod.nvidia.com/direct-sales-shop/DR/products/es_es/EUR/5438794800
> Error attempting to access URL: https://api-prod.nvidia.com/direct-sales-shop/DR/products/es_es/EUR/5438794800
> invalid character '<' looking for beginning of value
> ```
> 
> After that I tested with
> `.\nvidia-clerk-windows.exe -region=ESP -test`
> which got me:
> `Error attempting to access URL: https://api-prod.nvidia.com/direct-sales-shop/DR/products/es_es/EUR/`

**Comment by vic18t** [comment]
> Yeah version 2.4, It wasn't working before the 3090 launch either.

Have you tried deleting all copies of the app and reinstalling? No firewalls, No antivirus? Running as admin?

**Comment by HiramIII** [comment]
> 
> 
> > Yeah version 2.4, It wasn't working before the 3090 launch either.
> 
> Have you tried deleting all copies of the app and reinstalling? No firewalls, No antivirus? Running as admin?

I just deleted the .exe and reinstalled, disabled my antivirus as well still nothing. 

Here's my steps:

I go to the folder with the .exe in it
I then open a cmd in that folder
After that I run nvidia-clerk-windows.exe -region=USA -model=3080
Then that error comes up. Before the update to 2.4 that method worked.

**Comment by ibot4fun** [comment]
stopped working between 9:17 and 9:25 for me (EST). When i woke up it was perfectly normal. I'm PST so was asleep during the whole thing.

**Comment by ianmarmour** [comment]
This was basically NVIDIA's website going down, nothing I can do to work around it. The < error just means the response code you're getting from the NVIDIA store is empty (or you're requests was getting dropped) going to close this out as it's not an issue with Clerk itself.
