### ISSUE TITLE
Panic Runtime Error 

### ISSUE THREAD

**Issue by CoffeyJ83** [ianmarmour/nvidia-clerk#85]
Version 2.4 
Windows 10 
Running into error: 
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.main()
        /home/runner/work/nvidia-clerk/nvidia-clerk/main.go:99 +0xed3

Ran for a good couple hours and then got this error

**Comment by longgaminghours** [comment]
Yeah I am getting the same thing on Mac

**Comment by CoffeyJ83** [comment]
I just restarted it twice and it fixed the issue for now

**Comment by longgaminghours** [comment]
It’ll work for a few mins after restarting and do it again.

**Comment by CoffeyJ83** [comment]
Now getting them more frequently

**Comment by ianmarmour** [comment]
@CoffeyJ83 I'm assuming this is due to a response from NVIDIA that doesn't flag as an exception. I'm pushing a change for this right now.

**Comment by CoffeyJ83** [comment]
Thank you so much, I know you got your card yesterday, and you continuing to help out for the rest of us is amazing

**Comment by Fly1ngSquid** [comment]
@ianmarmour Unfortunately V 2.5 did not fix this issue for me. If anything it's popping up faster now.

Bandaid fix I'm running is a script to just restart the program if it runs into an error.

**Comment by ianmarmour** [comment]
https://github.com/ianmarmour/nvidia-clerk/releases/tag/v2.6

@CoffeyJ83 @Fly1ngSuid

**Comment by Fly1ngSquid** [comment]
Damn that was fast. Trying now. Thanks for all your hard work on this man.

**Comment by CoffeyJ83** [comment]
Running like a dream for me so far, many thanks again
