### ISSUE TITLE
Chrome does not open up  nvidia-clerk-windows.exe -region=DEU -model=3080

### ISSUE THREAD

**Issue by realfire23** [ianmarmour/nvidia-clerk#86]
hi,

chrome is not opened when not running test on USA. Is that supposed to be that way ?

nvidia-clerk-windows.exe -region=DEU -model=3080

browser only opens with

nvidia-clerk-windows.exe -region=USA -test

**Comment by b-lawler** [comment]
I also noticed this and assumed that changes were made so that it only opens when stock is found, and takes you to the Nvidia store link. Someone correct me if you are experiencing otherwise.

**Comment by CoffeyJ83** [comment]
It is working properly, when stock is reported it will open up the store page

**Comment by realfire23** [comment]
ok thank you.

I was struggling because in the documentation. After running the command dont close the chrome tab. That confused me.

Wouldnt it be better to have a chrome already open ?

**Comment by ianmarmour** [comment]
@realfire23 Nope it uses a special separate Chrome instance. I'll update the documentation to reflect the recent changes (sorry was trying to get the code pushed ASAP and didn't have time to update the documentation)

**Comment by ianmarmour** [comment]
Closing this out as it's not an issue.
