### ISSUE TITLE
error: Twilio: TWILIO_ACCOUNT_SID Environment variable not found

### ISSUE THREAD

**Issue by ibot4fun** [ianmarmour/nvidia-clerk#87]
Using new executable I'm seeing this error when attempting to run.
2020/09/24 12:41:57 Twilio: TWILIO_ACCOUNT_SID Environment variable not found

I disabled -SMS in the meantime

**Comment by vic18t** [comment]
> Using new executable I'm seeing this error when attempting to run.
> 2020/09/24 12:41:57 Twilio: TWILIO_ACCOUNT_SID Environment variable not found
> 
> I disabled -SMS in the meantime

Hmm working ok for me. Did you set your all your sms nvidia-clerk variables?

**Comment by ianmarmour** [comment]
@ibot4fun You probably didn't export your environment again (if you want it to be permanent you'll need to make sure the environment is setup permanently.

Windows Env Perm Setup
https://www.architectryan.com/2018/08/31/how-to-change-environment-variables-on-windows-10/

Linux/Mac
Add the commands to either your .zshrc, .bashrc in or .bash_profile in your home directory (you're mostly on your own here I believe in you)
