### ISSUE TITLE
Question/Feature request for ATC

### ISSUE THREAD

**Issue by vic18t** [ianmarmour/nvidia-clerk#88]
Can the browser launch with injected Javascript to add to cart? Or launch a modified version of the page?

Someone posted this on reddit:

Wanna feel special and see what it's like to have a 3090 in your cart? Go to the product page (https://www.nvidia.com/en-us/geforce/graphics-cards/30-series/rtx-3090/ ), press F12 (in Chrome), and paste this in to the console. You won't be able to check out (returns out of stock error), but maybe this will be of some use if there's another drop. Should work on the 3080 page too. I can't say for sure that this will help, but if other people are reporting an "Add to Cart" button and you're not seeing it, worth a try.

document.getElementsByClassName("cta-button btn show-out-of-stock stock-grey-out")[0].outerHTML = '<div class="cta-button btn show-out-of-stock js-add-button" data-nvnotify-form-path="null" data-theme-override="null">Add to cart</div>'; document.getElementsByClassName("cta-button btn show-out-of-stock js-add-button")[0].click()

**Comment by ianmarmour** [comment]
Don't you worry about a thing, release coming in about 5 mins that does you one better :)

**Comment by ianmarmour** [comment]
https://github.com/ianmarmour/nvidia-clerk/releases/tag/v3.0
