### ISSUE TITLE
invalid character 'E' looking for beginning of value

### ISSUE THREAD

**Issue by PedroC1999** [ianmarmour/nvidia-clerk#9]
Getting a loop of errors as shown below:

`
invalid character 'E' looking for beginning of value
Error getting SKU Information retrying...
`

My setup was as follows:
`
set NVIDIA_CLERK_LOCALE=en-gb
set NVIDIA_CLERK_SKU=5438792800
set NVIDIA_CLERK_CURRENCY=GBP
`

Any idea if it's something I'm doing wrong? Cheers!

**Comment by ianmarmour** [comment]
Can you try and update your locale to en_GB?

**Comment by ScottTHouston** [comment]
Can confirm this fixed the issue for me.

**Comment by PedroC1999** [comment]
This fixed it! Cheers for all your work

**Comment by callrua** [comment]
Try the following env:

set NVIDIA_CLERK_LOCALE=en_GB
set NVIDIA_CLERK_SKU=5438792800 
set NVIDIA_CLERK_CURRENCY=GBP

**Comment by ianmarmour** [comment]
Glad to hear it, going to close out this issue now, good luck with the purchase.
