### ISSUE TITLE
Latest Version SMS TEST Not Working

### ISSUE THREAD

**Issue by KaZaKiE** [ianmarmour/nvidia-clerk#90]
In the latest version the -sms -test parameters cause the bot to search for a 3080, attempt to add it to cart and then fail. The SMS test is never completed because I assume the add to cart failure causes a hard crash, given the 3080 is currently unavailable.

**Comment by vic18t** [comment]
Use -model=2060 flag to test

**Comment by ianmarmour** [comment]
Also if you want to test clicking the link on your mobile device you need to use the -remote flag (the link can only be used once to either open a desktop browser or a mobile one)
