### ISSUE TITLE
Weblink in sms text alert does not add item to cart

### ISSUE THREAD

**Issue by vic18t** [ianmarmour/nvidia-clerk#91]
Tried with both Safari and Chrome mobile browsers. Only works on desktop browser.

**Comment by ianmarmour** [comment]
You need to enable -remote flag, the link can only be used a single time so if you let the browser open on your desktop it breaks mobile devices.

**Comment by ianmarmour** [comment]
I know this isn't incredibly intuitive but I didn't want to break behavior for existing users.

**Comment by CoffeyJ83** [comment]
@ianmarmour Would you release 2.6 would still be a good safe bet incase Nvidia changes up anything before the next batch of cards?

**Comment by noriea** [comment]
Same issue, but with Discord. I set my discord webhook then run
nvidia-clerk-windows.exe -model=2060 -discord -remote. 
Get the notification and click the link, but takes me to an empty cart. Removing -remote makes the auto-popup cart page work, but coinciding Discord link still doesn't.

**Comment by ianmarmour** [comment]
@noriea I just tested it myself with discord and it's working fine I'm not quite sure why you would be getting any different behavior then me...

**Comment by ianmarmour** [comment]
@noriea I also verified SMS functionality as well so I'm really not sure as to what could be going on for you? Dumb question but you have the latest release right 3.0?

**Comment by noriea** [comment]
Yup just re-downloaded to be super sure and tried it with default browser set to edge in case it was a cookie/cache issue (haven't used edge yet). I also tried a fresh discord link on my phone. Same thing. Removing -remote and -discord works with the immediate browser popup only. Does order of the commands matter? Essentially I would want mine to be -
nvidia-clerk-windows.exe -discord -region=USA -model=3080 -remote (I'm using model=2070 with these tests)

**Comment by noriea** [comment]
The above command gives me:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x81601f]

goroutine 1 [running]:
main.main()
        /home/runner/work/nvidia-clerk/nvidia-clerk/main.go:53 +0x55f

**Comment by ianmarmour** [comment]
@noriea model=2070 <<< needs to be a 2060, there's no config entry for 2070

**Comment by ianmarmour** [comment]
No argument ordering does not matter.

**Comment by noriea** [comment]
Sorry, typo. That was that issue, still empty cart when I change the 6 to a 7.

**Comment by ianmarmour** [comment]
Just want to clarify, the browser popup shows the item in your cart?

**Comment by noriea** [comment]
Yes, but only if I remove the -discord AND -remote arguments.

**Comment by noriea** [comment]
I could invite you to this discord for a moment and try the link yourself if you like.

**Comment by ianmarmour** [comment]
Sure

**Comment by noriea** [comment]
[https://discord.gg/zmQttU](url)  "Info" channel. I'll trigger a link now and not click it.

**Comment by vic18t** [comment]
> You need to enable -remote flag, the link can only be used a single time so if you let the browser open on your desktop it breaks mobile devices.

@ianmarmour If I create two instances of the app, one with -remote and without, would both the browser and (other) mobile link work?

**Comment by ianmarmour** [comment]
@vic18t I don't see why not

I think the alerts are slightly broken right now (due to a character encoding bug... sigh)

**Comment by ndemos** [comment]
The sms link is also not working for me.

nvidia-clerk-windows.exe -region=USA -model=2060 -delay=1000
This command opens the browser and adds the item to the cart.

nvidia-clerk-windows.exe -region=USA -model=2060 -delay=1000 -sms -remote
This command either sends an sms with a link to an empty cart or fails to send an sms and passes the error "Error adding card to checkout."

**Comment by ianmarmour** [comment]
Just resolved this issue locally was a character encoding issue.

**Comment by ianmarmour** [comment]
Pushing a fix for this and the discord issue right now (this one sucked haha)

**Comment by ianmarmour** [comment]
It does now :)

https://github.com/ianmarmour/nvidia-clerk/releases/tag/v3.2
