### ISSUE TITLE
Unable to Use Discord Webhook or Chrome Browser

### ISSUE THREAD

**Issue by Brothajiff** [ianmarmour/nvidia-clerk#92]
When I run the nvidia-clerk-windows.exe with the correct parameters it does check in CMD prompt for the existence of the stock. However, it does not open a chrome window (even with test). I also configured a webhook in my discord which appears to process but does not actually send anything. I am not sure what I am doing wrong. I appreciate any help. These are the test batch files I am using: 

DISCORD TEST:
set DISCORD_WEBHOOK_URL="https://discordapp.com/api/webhooks/758812272474062859/Oz8JeHgOceiM8meyWZA3MdCwqU5y1XCJJV-PHKDm-wQk9z9CoqDQqeb8fhwVukkBWJ3p"
.\nvidia-clerk-windows.exe -discord -test

STANDARD TEST: 
.\nvidia-clerk-windows.exe --region=USA -test

**Comment by ianmarmour** [comment]
.\nvidia-clerk-windows.exe --region=USA -test -model=2060

**Comment by ianmarmour** [comment]
It won't open the browser because it can't open the browser with the 3080, the request will fail to add to cart, the 2060 won't however so try with that.

**Comment by Brothajiff** [comment]
Great that did work for opening the browser. Sorry I must have misunderstood. I can try the same for the discord webhook.

**Comment by ianmarmour** [comment]
If you want to run the webhook and use the URL you need to use -remote as well, if you just want the notification but for it to still open your browser then leave the -remote off.

**Comment by ianmarmour** [comment]
with link

.\nvidia-clerk-windows.exe --region=USA -test -model=2060 -discord -remote

without working link

.\nvidia-clerk-windows.exe --region=USA -test -model=2060 -discord

**Comment by Brothajiff** [comment]
Great thank you got it all working. Really amazing stuff you're doing here. It's sad that it is necessary but I guess this is where we are in the scheme of things. I really appreciate all your work and thank you for sharing and helping.

**Comment by ianmarmour** [comment]
Discord fix is here for -remote https://github.com/ianmarmour/nvidia-clerk/releases/tag/v3.2
