### ISSUE TITLE
New Chrome Window does not launch

### ISSUE THREAD

**Issue by yumotto** [ianmarmour/nvidia-clerk#93]
Operating system: Windows 10

Version of nvidia-clerk: v3.0

Parameters passed in: -region=USA -model=3080

Additional info:
So following the README instructions, and after previously using v0.4, the new chrome window does not launch after writing the "nvidia-clerk-windows.exe -region=USA -model=3080" command. However, everything goes smoothly in the command prompt. 

I tried restarting and reinstalling the same version but it still happens. 

Help is greatly appreciated
Thanks in advance!

**Comment by ianmarmour** [comment]
Not a bug this is the intended usage, it only opens the window when you're ready to checkout now. If you want to test how this works try,

nvidia-clerk-windows.exe -region=USA -model=2060 -test

**Comment by yumotto** [comment]
> Not a bug this is the intended usage, it only opens the window when you're ready to checkout now. If you want to test how this works try,
> 
> nvidia-clerk-windows.exe -region=USA -model=2060 -test


Yes! I just tested it but thank you for clarifying anyways. I was trying the same test command but with a 2070 instead of 2060 and was also getting an error. The "nvidia-clerk-windows.exe -region=USA -model=2060 -test" test command works though.
