### ISSUE TITLE
Chrome doesn't open.

### ISSUE THREAD

**Issue by CPYY** [ianmarmour/nvidia-clerk#94]
First of all you my friend are a hero for doing this so thank you.

Windows 10 Version 2004.
Nvidia-clerk version 3.0
Running 
nvidia-clerk-windows.exe -region=USA -test
nvidia-clerk-windows.exe -region=USA -model=3080
Both started via Cmd but they don't open google chrome.
![1](https://user-images.githubusercontent.com/71854602/94208373-be76be00-feda-11ea-9f6a-4998368fbef0.png)
![2](https://user-images.githubusercontent.com/71854602/94208378-c171ae80-feda-11ea-9c75-677864f99544.png)

**Comment by ianmarmour** [comment]
nvidia-clerk-windows.exe -region=USA -model=2060 -test

It will fail to add to cart because the 3080 is not in stock, try the above command instead to test how this works.

**Comment by CPYY** [comment]
> nvidia-clerk-windows.exe -region=USA -model=2060 -test
> 
> It will fail to add to cart because the 3080 is not in stock, try the above command instead to test how this works.

It works perfectly thank you for the quick reply and have a good day.
