### ISSUE TITLE
Telegram test fails

### ISSUE THREAD

**Issue by StanleyAlbayeros** [ianmarmour/nvidia-clerk#96]
It was working before the latest release. I get the following message: 

```
.\nvidia-clerk-windows.exe -region=ESP -model=2060 -test -telegram
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x1065d11]

goroutine 1 [running]:
main.main()
        /home/runner/work/nvidia-clerk/nvidia-clerk/main.go:62 +0x5d1
```

**Comment by ianmarmour** [comment]
You need to use the -model=2060 to test and it only works in the US region (no 2060 model id for spain yet it used to default to US but I didn't like that behavior)

**Comment by LOX311** [comment]
> You need to use the -model=2060 to test and it only works in the US region (no 2060 model id for spain yet it used to default to US but I didn't like that behavior)

Hello again!
One quick question.
I have the 3.1 version running, with the Auto Checkout dose it mean i leave it runing and it will auto buy and pay the crad for me?
I have set my cc on nvidia and its logged in also.

**Comment by gamingarena23** [comment]
When you use -discord -model=2060

it opens up the link in disocrd which i guess it works as it should but the link that opens up in chrome in new tab is not item in the cart but empty cart with message "your shopping carts is currently empty"

**Comment by ianmarmour** [comment]
@gamingarena23 

https://github.com/ianmarmour/nvidia-clerk/releases/tag/v3.2

Here's a fix for the empty cart with discord/sms (there was a crazy bug regarding what character encoding they accept)
