### ISSUE TITLE
URL not working

### ISSUE THREAD

**Issue by reubenprevost** [ianmarmour/nvidia-clerk#97]
v3.1

Actually, it seems that the URL is only failing to work with the -remote flag. I'll continue testing this. I'm not sure why it's not working.

--edit--

I think I've narrowed the problem down. When using discord alerts, the link fails with and without the remote flag. Possibly because discord is sending a request to the page before the user actually uses it?

So, the url fails to work when using the discord flag

**Comment by reubenprevost** [comment]
I removed the link from the discord alert and it worked fine. That removes the functionality of the remote flag, but atleast I can receive discord alerts.

So, let me summarize

-discord flag breaks the cart URL with and without the remote flag.
-removing the url from the discord alert fixes the problem.

**Comment by ianmarmour** [comment]
https://github.com/ianmarmour/nvidia-clerk/releases/tag/v3.2

This is the fix there was issues with character encoding (wild stuff)
