### ISSUE TITLE
Doesn't launch a Chrome window after starting

### ISSUE THREAD

**Issue by phastekk** [ianmarmour/nvidia-clerk#98]

**Comment by Qerlak** [comment]
That is intentional. Once a card is ready to purchase, it will open a new tab in your default browser with the card in your cart. It does not open a tab if the card is out of stock.

**Comment by Qerlak** [comment]
you can test this with the "-model=2060" option. It will open a new tab in chrome with it ready to buy in your cart! Hope this helps
