### ISSUE TITLE
Discord links are still broken with v3.2

### ISSUE THREAD

**Issue by Qerlak** [ianmarmour/nvidia-clerk#99]
Operating system: Windows 10/iOS
Version of nvidia-clerk you're running: fresh off the press v3.2
Parameters passed in (redact sensitive info): nvidia-clerk-windows.exe -discord -region=USA -model=2060 -remote
Additional info:
With or without the '-remote' tag, the link sent to my discord channel does not work on my desktop computer nor my iPhone. Both say "Your shopping cart is currently empty." Tried deleting and reinstalling program, no bueno. Not a huge deal as I work from home and am at this computer most of the day, but just wanted to bring it up for others. Omitting the -remote tag and just letting the command line open the chrome tab works great, rtx 2060 in cart and ready to check out.

**Comment by fokeiro2020** [comment]
> Operating system: Windows 10/iOS
> Version of nvidia-clerk you're running: fresh of the press v3.2
> Parameters passed in (redact sensitive info): nvidia-clerk-windows.exe -discord -region=USA -model=2060 -remote
> Additional info:
> With or without the '-remote' tag, the link sent to my discord channel does not work on my desktop computer nor my iPhone. Both say "Your shopping cart is currently empty." Tried deleting and reinstalling program, no bueno. Not a huge deal as I work from home and am at this computer most of the day, but just wanted to bring it up for others. Omitting the -remote tag and just letting the command line open the chrome tab works great, rtx 2060 in cart and ready to check out.

same behavior

**Comment by Qerlak** [comment]
Ok I would like to clarify--Not having the -remote tag removes the link from the discord message, so that is working as intended, but including the -remote tag sends a broken link just like in previous versions.

**Comment by ianmarmour** [comment]
Fix is released now! @Qerlak @fokeiro2020 closing this now (discord was crawling the links and taking our sessions away, if you're an android user disable message previews as well to avoid this for SMS)
